import React,{useMemo,useRef,useState}from"react";
import VideoAdStudioV2 from"./VideoAdStudioV2.jsx";

const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#55dcff",purple:"#9a5cff",line:"rgba(113,157,255,.22)",panel:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const card={border:`1px solid ${C.line}`,borderRadius:18,background:C.panel,padding:15};
const input={width:"100%",boxSizing:"border-box",padding:"12px 13px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:14,outline:"none"};
const btn={padding:"12px 13px",border:0,borderRadius:13,background:"linear-gradient(135deg,#8739ef,#197fe2 58%,#16c6e8)",color:"white",fontWeight:900,fontSize:13};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=p=>{p=clamp(p);return p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2};

function dims(r){if(r==="16:9")return[960,540];if(r==="1:1")return[720,720];return[540,960]}
function recorderMime(){const a=["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"];return a.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}
function rounded(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function lines(ctx,text,maxWidth,maxLines=2){const words=String(text||"").trim().split(/\s+/).filter(Boolean),out=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(line&&ctx.measureText(test).width>maxWidth){out.push(line);line=word;if(out.length>=maxLines)break}else line=test}if(line&&out.length<maxLines)out.push(line);return out}
function drawLines(ctx,text,x,y,maxWidth,lineHeight,maxLines=2,align="left"){ctx.textAlign=align;lines(ctx,text,maxWidth,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight))}

function motion(progress,index,preset){const p=ease(progress),flip=index%2?1:-1;if(preset==="Punchy")return{z:1.1+.1*Math.sin(p*Math.PI),x:flip*.07*(1-p),y:-.02+.04*p,r:flip*.012*Math.sin(p*Math.PI)};if(preset==="Product")return{z:1.04+.08*p,x:-flip*.025+.05*flip*p,y:.025-.04*p,r:0};if(preset==="Smooth")return{z:1.08+.035*p,x:flip*.025-.05*flip*p,y:0,r:flip*.004*Math.sin(p*Math.PI)};if(preset==="Static")return{z:1.03,x:0,y:0,r:0};const mode=index%4;if(mode===0)return{z:1.03+.14*p,x:.04-.08*p,y:.02-.035*p,r:-.005*Math.sin(p*Math.PI)};if(mode===1)return{z:1.17-.12*p,x:-.035+.065*p,y:-.025+.04*p,r:.006*Math.sin(p*Math.PI)};if(mode===2)return{z:1.08+.05*Math.sin(p*Math.PI),x:-.07+.14*p,y:0,r:0};return{z:1.06+.07*p,x:.065-.13*p,y:.03-.05*p,r:.004*Math.sin(p*Math.PI)}
}

function cover(ctx,source,w,h,progress,index,preset){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)return;const base=Math.max(w/sw,h/sh);ctx.save();ctx.filter="blur(24px) brightness(.48) saturate(.82)";const bg=base*1.2;ctx.drawImage(source,(w-sw*bg)/2,(h-sh*bg)/2,sw*bg,sh*bg);ctx.restore();const m=motion(progress,index,preset),scale=base*m.z,dw=sw*scale,dh=sh*scale,x=(w-dw)/2+m.x*w,y=(h-dh)/2+m.y*h;ctx.save();ctx.translate(w/2,h/2);ctx.rotate(m.r);ctx.translate(-w/2,-h/2);ctx.drawImage(source,x,y,dw,dh);ctx.restore()}

function transitionOverlay(ctx,w,h,p,type,index){if(type==="None")return;const edge=Math.min(p/.12,(1-p)/.12),strength=1-clamp(edge);if(strength<=0)return;if(type==="Flash"){ctx.fillStyle=`rgba(255,255,255,${strength*.48})`;ctx.fillRect(0,0,w,h);return}if(type==="Swipe"){const dir=index%2?1:-1,x=dir>0?(-w+strength*w):(w-strength*w);ctx.fillStyle=`rgba(4,11,28,${.92*strength})`;ctx.fillRect(x,0,w,h);return}ctx.fillStyle=`rgba(3,9,24,${strength*.72})`;ctx.fillRect(0,0,w,h)}

function drawFrame(ctx,source,w,h,p,index,total,form,style){ctx.fillStyle="#071329";ctx.fillRect(0,0,w,h);cover(ctx,source,w,h,p,index,style.motion);const sweep=(-.25+1.5*p)*w,g=ctx.createLinearGradient(sweep-w*.18,0,sweep+w*.18,0);g.addColorStop(0,"rgba(255,255,255,0)");g.addColorStop(.5,"rgba(120,210,255,.08)");g.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 const shade=ctx.createLinearGradient(0,0,0,h);shade.addColorStop(0,style.textPosition==="Top"?"rgba(2,8,22,.82)":"rgba(2,8,22,.12)");shade.addColorStop(.45,"rgba(2,8,22,.08)");shade.addColorStop(1,style.textPosition==="Bottom"?"rgba(2,8,22,.88)":"rgba(2,8,22,.36)");ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);
 const pad=Math.round(w*.065),center=style.textPosition==="Middle",top=style.textPosition==="Top",baseY=top?h*.13:center?h*.42:h*.69,x=center?w/2:pad,align=center?"center":"left",max=w-pad*2;
 ctx.textAlign=align;ctx.fillStyle="#fff";ctx.shadowColor="rgba(0,0,0,.55)";ctx.shadowBlur=12;ctx.font=`900 ${Math.round(w*.071)}px system-ui,sans-serif`;drawLines(ctx,form.headline||form.title||"Your Ad",x,baseY,max,Math.round(w*.079),2,align);ctx.shadowBlur=8;ctx.fillStyle="rgba(255,255,255,.92)";ctx.font=`600 ${Math.round(w*.035)}px system-ui,sans-serif`;drawLines(ctx,form.subtext||"",x,baseY+Math.round(w*.19),max,Math.round(w*.048),2,align);ctx.shadowBlur=0;
 const cta=form.cta||"Message us today";ctx.font=`800 ${Math.round(w*.032)}px system-ui,sans-serif`;const tw=ctx.measureText(cta).width,ph=Math.round(w*.04),pv=Math.round(w*.023),boxW=Math.min(max,tw+ph*2),boxH=Math.round(w*.092),boxX=center?(w-boxW)/2:pad,boxY=top?baseY+Math.round(w*.31):center?baseY+Math.round(w*.31):h-pad-boxH;const cg=ctx.createLinearGradient(boxX,0,boxX+boxW,0);cg.addColorStop(0,"#8d35ff");cg.addColorStop(1,"#14c8ec");ctx.fillStyle=cg;rounded(ctx,boxX,boxY,boxW,boxH,Math.round(w*.028));ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText(cta,boxX+boxW/2,boxY+boxH*.65);
 ctx.fillStyle="rgba(255,255,255,.72)";ctx.font=`700 ${Math.round(w*.022)}px system-ui,sans-serif`;ctx.textAlign="right";ctx.fillText(`${index+1}/${total}`,w-pad,pad+Math.round(w*.02));transitionOverlay(ctx,w,h,p,style.transition,index)
}

async function loadMedia(file){const url=URL.createObjectURL(file);if(file.type.startsWith("video/")){const v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((ok,bad)=>{v.onloadedmetadata=ok;v.onerror=()=>bad(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}const img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}

function Chip({active,onClick,children}){return <button type="button" onClick={onClick} style={{padding:"9px 10px",borderRadius:11,border:`1px solid ${active?"#58dfff":C.line}`,background:active?"linear-gradient(135deg,rgba(126,58,239,.8),rgba(28,135,217,.8))":"rgba(255,255,255,.035)",color:C.text,fontSize:11,fontWeight:850}}>{children}</button>}

export default function EnhancedFreeMotion({profile={}}){
 const[fileRef,setFileRef]=useState(null),canvasRef=useRef(null);const[editor,setEditor]=useState("enhanced");
 const[form,setForm]=useState({title:profile.business?`${profile.business} Ad`:"",headline:profile.business||"Your Business",subtext:profile.product||"Show customers what makes you different",cta:"Message us today",duration:"10",ratio:"9:16"});
 const[style,setStyle]=useState({motion:"Cinematic",transition:"Fade",pacing:"Balanced",textPosition:"Bottom"});const[media,setMedia]=useState([]),[video,setVideo]=useState(null),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const setF=(k,v)=>setForm(s=>({...s,[k]:v})),setS=(k,v)=>setStyle(s=>({...s,[k]:v}));const sceneSeconds=style.pacing==="Quick"?1.8:style.pacing==="Slow"?4.2:2.8;
 const sceneEstimate=useMemo(()=>Math.max(media.length||1,Math.ceil(Number(form.duration||10)/sceneSeconds)),[media.length,form.duration,sceneSeconds]);
 function choose(e){const picked=Array.from(e.target.files||[]).slice(0,8);media.forEach(x=>URL.revokeObjectURL(x.url));setMedia(picked.map(file=>({file,url:URL.createObjectURL(file),video:file.type.startsWith("video/")})));if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);setError("");setStatus(picked.length?`${picked.length} media item${picked.length===1?"":"s"} ready`:"Ready")}
 function remove(i){setMedia(items=>{const t=items[i];if(t?.url)URL.revokeObjectURL(t.url);return items.filter((_,n)=>n!==i)})}
 async function render(){if(!media.length)return setError("Upload at least one photo or short video first.");if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)return setError("Video export is not supported in this browser. Try Chrome on Android or desktop.");setBusy(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);setStatus("Preparing media…");const loaded=[];try{for(const m of media)loaded.push(await loadMedia(m.file));const[w,h]=dims(form.ratio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=recorderMime(),chunks=[],rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_500_000}:{videoBitsPerSecond:4_500_000});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const done=new Promise((ok,bad)=>{rec.onstop=ok;rec.onerror=e=>bad(e.error||new Error("Export failed"))});rec.start(250);const totalMs=Math.max(3000,Number(form.duration||10)*1000),sceneCount=Math.max(loaded.length,Math.ceil(totalMs/(sceneSeconds*1000))),slot=totalMs/sceneCount;
  for(let i=0;i<sceneCount;i++){const item=loaded[i%loaded.length],start=performance.now(),end=start+slot;if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{}}while(performance.now()<end){const p=clamp((performance.now()-start)/slot);drawFrame(ctx,item.source,w,h,p,i,sceneCount,form,style);await sleep(33)}if(item.type==="video")item.source.pause();setStatus(`Rendering scene ${i+1} of ${sceneCount}…`)}rec.stop();await done;const outMime=rec.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:outMime}),url=URL.createObjectURL(blob),ext=outMime.includes("mp4")?"mp4":"webm";setVideo({url,ext,size:blob.size,name:`bizai-${(form.title||"free-motion-ad").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"free-motion-ad"}.${ext}`});setStatus(`${ext.toUpperCase()} ready · ${style.motion} motion · ${style.transition} transition`)}catch(e){setError(e.message||"Could not create video.");setStatus("Render stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusy(false)}}
 if(editor==="classic")return <div><div style={{padding:"14px 18px 0",display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Chip active={false} onClick={()=>setEditor("enhanced")}>✨ Enhanced</Chip><Chip active onClick={()=>{}}>Classic</Chip></div><VideoAdStudioV2 profile={profile}/></div>;
 return <main style={{padding:"15px 18px 50px",display:"grid",gap:14,color:C.text}}>
  <section style={{...card,border:"1px solid rgba(82,216,255,.38)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><div style={{fontSize:10,color:C.cyan,fontWeight:900}}>FREE MOTION · ENHANCED</div><div style={{fontSize:20,fontWeight:950,marginTop:5}}>Ad Motion Studio</div><div style={{fontSize:11,color:C.muted,marginTop:4,lineHeight:1.45}}>Turn your own photos and clips into a polished short ad directly on your device.</div></div><span style={{fontSize:24}}>🎬</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><Chip active onClick={()=>{}}>✨ Enhanced</Chip><Chip active={false} onClick={()=>setEditor("classic")}>Classic fallback</Chip></div></section>

  <section style={{...card,display:"grid",gap:10}}><div style={{fontSize:11,fontWeight:900,color:C.cyan}}>1 · AD COPY</div><input style={input} value={form.title} onChange={e=>setF("title",e.target.value)} placeholder="Project name"/><input style={input} value={form.headline} onChange={e=>setF("headline",e.target.value)} placeholder="Headline"/><textarea style={{...input,resize:"vertical",minHeight:72}} value={form.subtext} onChange={e=>setF("subtext",e.target.value)} placeholder="Short supporting text"/><input style={input} value={form.cta} onChange={e=>setF("cta",e.target.value)} placeholder="Call to action"/></section>

  <section style={{...card,display:"grid",gap:12}}><div style={{fontSize:11,fontWeight:900,color:C.cyan}}>2 · MEDIA</div><input ref={el=>{if(el&&!fileRef)setFileRef(el)}} type="file" accept="image/*,video/*" multiple onChange={choose} style={{...input,padding:10}}/><div style={{fontSize:10,color:C.muted}}>Up to 8 photos or short video clips. Files stay on your device while this free renderer works.</div>{media.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>{media.map((m,i)=><div key={m.url} style={{position:"relative",aspectRatio:"1",borderRadius:10,overflow:"hidden",border:`1px solid ${C.line}`,background:"#071329"}}>{m.video?<video src={m.url} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={m.url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>}<button onClick={()=>remove(i)} style={{position:"absolute",right:3,top:3,width:23,height:23,borderRadius:99,border:0,background:"rgba(0,0,0,.72)",color:"white"}}>×</button></div>)}</div>}</section>

  <section style={{...card,display:"grid",gap:13}}><div style={{fontSize:11,fontWeight:900,color:C.cyan}}>3 · STYLE & TIMING</div><div><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:6}}>MOTION PRESET</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{["Cinematic","Punchy","Product","Smooth","Static"].map(x=><Chip key={x} active={style.motion===x} onClick={()=>setS("motion",x)}>{x}</Chip>)}</div></div><div><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:6}}>TRANSITION</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>{["Fade","Flash","Swipe","None"].map(x=><Chip key={x} active={style.transition===x} onClick={()=>setS("transition",x)}>{x}</Chip>)}</div></div><div><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:6}}>PACING</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{["Quick","Balanced","Slow"].map(x=><Chip key={x} active={style.pacing===x} onClick={()=>setS("pacing",x)}>{x}</Chip>)}</div></div><div><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:6}}>TEXT POSITION</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{["Top","Middle","Bottom"].map(x=><Chip key={x} active={style.textPosition===x} onClick={()=>setS("textPosition",x)}>{x}</Chip>)}</div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>DURATION</div><select style={input} value={form.duration} onChange={e=>setF("duration",e.target.value)}>{[5,10,15,30].map(x=><option key={x} value={x}>{x} seconds</option>)}</select></label><label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>FORMAT</div><select style={input} value={form.ratio} onChange={e=>setF("ratio",e.target.value)}><option value="9:16">9:16 Vertical</option><option value="1:1">1:1 Square</option><option value="16:9">16:9 Landscape</option></select></label></div><div style={{fontSize:11,color:"#bfd0eb"}}>Estimated scenes: <b>{sceneEstimate}</b> · {style.pacing} pacing · visual-only export</div></section>

  <section style={{...card,display:"grid",gap:10}}><div style={{fontSize:11,fontWeight:900,color:C.cyan}}>4 · CREATE</div><button disabled={busy||!media.length} onClick={render} style={{...btn,opacity:busy||!media.length?.55:1}}>{busy?status:"Create Free Motion Ad"}</button><div style={{fontSize:10,color:C.muted,lineHeight:1.5}}>No paid API is used. Free Motion renders locally in your browser. Add music/voice later in an editor; this export is intentionally visual-only.</div>{error&&<div style={{padding:10,borderRadius:11,border:"1px solid rgba(255,92,118,.32)",background:"rgba(100,18,38,.18)",color:"#ffbac5",fontSize:11}}>{error}</div>}{!busy&&status!=="Ready"&&<div style={{fontSize:11,color:C.cyan,fontWeight:800,textAlign:"center"}}>{status}</div>}</section>

  {video&&<section style={{...card,display:"grid",gap:10,border:"1px solid rgba(77,224,159,.35)"}}><div style={{fontSize:11,fontWeight:900,color:"#79efb2"}}>VIDEO READY</div><video src={video.url} controls playsInline style={{width:"100%",maxHeight:560,borderRadius:14,background:"#000"}}/><a href={video.url} download={video.name} style={{...btn,textAlign:"center",textDecoration:"none"}}>Download {video.ext.toUpperCase()}</a><div style={{fontSize:10,color:C.muted,textAlign:"center"}}>{(video.size/1024/1024).toFixed(1)} MB · {form.ratio} · {form.duration}s</div></section>}
  <canvas ref={canvasRef} style={{display:"none"}}/>
 </main>
}
