import React,{useMemo,useRef,useState}from"react";

const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#54ddff",purple:"#9a5cff",line:"rgba(113,157,255,.22)",panel:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const input={width:"100%",boxSizing:"border-box",padding:"13px 14px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:14,outline:"none"};
const card={borderRadius:18,border:`1px solid ${C.line}`,background:C.panel,padding:15};
const btn={border:0,borderRadius:13,padding:"12px 14px",fontWeight:900,color:"white",background:"linear-gradient(135deg,#873aff,#2f79ef 55%,#20c9df)"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=p=>{p=clamp(p);return p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2};

function dimensions(r){if(r==="16:9")return[960,540];if(r==="1:1")return[720,720];return[540,960]}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?.(x,y,w,h,r);if(!ctx.roundRect){ctx.rect(x,y,w,h)}ctx.closePath()}
function wrap(ctx,text,x,y,max,lineH,maxLines=2){const words=String(text||"").split(/\s+/).filter(Boolean);let lines=[],line="";for(const word of words){const t=line?line+" "+word:word;if(ctx.measureText(t).width>max&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=t}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((s,i)=>ctx.fillText(s,x,y+i*lineH))}
function pickMime(){const list=["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"];return list.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}

function transform(p,scene,preset,intensity){const e=ease(p),k=Number(intensity||1),dir=scene%2?1:-1;if(preset==="Push In")return{z:1.02+.17*e*k,x:.025*dir*(1-e),y:.018*Math.sin(e*Math.PI)};if(preset==="Pull Out")return{z:1.20-.16*e*k,x:.025*dir*e,y:-.02+.04*e};if(preset==="Pan")return{z:1.10,x:(-.08+.16*e)*dir*k,y:.02*Math.sin(e*Math.PI)};if(preset==="Orbit")return{z:1.08+.035*Math.sin(e*Math.PI),x:.045*Math.cos(e*Math.PI*2+scene),y:.03*Math.sin(e*Math.PI*2+scene)};if(preset==="Punchy")return{z:1.04+.10*Math.sin(Math.min(1,e*1.4)*Math.PI/2)*k,x:.035*dir*(1-e),y:-.025+.05*e};const m=scene%5;if(m===0)return{z:1.03+.14*e*k,x:.03-.06*e,y:.01-.02*e};if(m===1)return{z:1.17-.12*e*k,x:-.04+.08*e,y:-.02+.04*e};if(m===2)return{z:1.09,x:-.08+.16*e,y:0};if(m===3)return{z:1.08+.05*e,x:.08-.16*e,y:.025-.05*e};return{z:1.05+.11*e,x:-.025+.05*e,y:.055-.1*e}}

function drawMedia(ctx,source,w,h,p,scene,preset,intensity){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)return;const base=Math.max(w/sw,h/sh);ctx.save();ctx.filter="blur(24px) brightness(.5) saturate(.95)";const bz=base*1.18;ctx.drawImage(source,(w-sw*bz)/2,(h-sh*bz)/2,sw*bz,sh*bz);ctx.restore();const t=transform(p,scene,preset,intensity),s=base*t.z,dw=sw*s,dh=sh*s;ctx.save();ctx.translate(w/2,h/2);ctx.rotate((scene%2?1:-1)*.008*Math.sin(p*Math.PI)*Number(intensity||1));ctx.translate(-w/2,-h/2);ctx.drawImage(source,(w-dw)/2+t.x*w,(h-dh)/2+t.y*h,dw,dh);ctx.restore()}

function transitionOverlay(ctx,w,h,p,type){const edge=.10;if(type==="Cut")return;let a=p<edge?1-p/edge:p>1-edge?(p-(1-edge))/edge:0;a=clamp(a);if(!a)return;if(type==="Flash"){ctx.fillStyle=`rgba(235,248,255,${a*.7})`;ctx.fillRect(0,0,w,h);return}if(type==="Wipe"){ctx.fillStyle=`rgba(5,12,30,${a*.85})`;const ww=w*a;ctx.fillRect(p<.5?0:w-ww,0,ww,h);return}ctx.fillStyle=`rgba(5,12,30,${a*.72})`;ctx.fillRect(0,0,w,h)}

function drawText(ctx,w,h,form,p){const pos=form.textPosition||"Bottom",pad=Math.round(w*.065);const anchor=pos==="Top"?h*.14:pos==="Center"?h*.46:h*.72;const dark=ctx.createLinearGradient(0,anchor-h*.18,0,Math.min(h,anchor+h*.28));dark.addColorStop(0,"rgba(2,8,22,0)");dark.addColorStop(1,"rgba(2,8,22,.88)");ctx.fillStyle=dark;ctx.fillRect(0,Math.max(0,anchor-h*.22),w,Math.min(h,h-anchor+h*.22));ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.074)}px system-ui,sans-serif`;wrap(ctx,form.headline||"Your Ad",pad,anchor,w-pad*2,Math.round(w*.083),2);ctx.font=`600 ${Math.round(w*.034)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.9)";wrap(ctx,form.subtext||"",pad,anchor+Math.round(w*.18),w-pad*2,Math.round(w*.047),2);const cta=form.cta||"Message us today";ctx.font=`800 ${Math.round(w*.032)}px system-ui,sans-serif`;const tw=ctx.measureText(cta).width,ph=Math.round(w*.04),bh=Math.round(w*.105);let by=pos==="Top"?anchor+Math.round(w*.30):pos==="Center"?anchor+Math.round(w*.31):h-pad-bh;by=Math.min(h-pad-bh,by);const bw=Math.min(w-pad*2,tw+ph*2);const g=ctx.createLinearGradient(pad,0,pad+bw,0);g.addColorStop(0,"#8d35ff");g.addColorStop(1,"#13c9ef");ctx.fillStyle=g;rounded(ctx,pad,by,bw,bh,Math.round(w*.03));ctx.fill();ctx.fillStyle="#fff";ctx.fillText(cta,pad+ph,by+Math.round(bh*.68));ctx.fillStyle="rgba(255,255,255,.7)";ctx.font=`700 ${Math.round(w*.021)}px system-ui,sans-serif`;ctx.fillText("BIZAI FREE MOTION",pad,pad+Math.round(w*.025))}

function drawFrame(ctx,source,w,h,form,scene,total,p){ctx.fillStyle="#071329";ctx.fillRect(0,0,w,h);drawMedia(ctx,source,w,h,p,scene,form.motion,form.intensity);const lx=(-.3+1.6*p)*w,shine=ctx.createLinearGradient(lx-w*.16,0,lx+w*.16,0);shine.addColorStop(0,"rgba(255,255,255,0)");shine.addColorStop(.5,"rgba(130,210,255,.08)");shine.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=shine;ctx.fillRect(0,0,w,h);drawText(ctx,w,h,form,p);ctx.fillStyle="rgba(255,255,255,.76)";ctx.font=`700 ${Math.round(w*.022)}px system-ui,sans-serif`;ctx.fillText(`${scene+1}/${total}`,w-Math.round(w*.12),Math.round(w*.08));transitionOverlay(ctx,w,h,p,form.transition)}

async function imageItem(file){const url=URL.createObjectURL(file),img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}
async function videoItem(file){const url=URL.createObjectURL(file),v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=()=>rej(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}

function Pill({active,onClick,children}){return <button type="button" onClick={onClick} style={{padding:"9px 11px",borderRadius:11,border:`1px solid ${active?"#64def7":C.line}`,background:active?"linear-gradient(135deg,rgba(132,58,255,.9),rgba(27,157,218,.9))":"rgba(255,255,255,.035)",color:C.text,fontWeight:850,fontSize:11}}>{children}</button>}
function Label({children}){return <div style={{fontSize:10,color:C.muted,fontWeight:900,letterSpacing:.35,marginBottom:6}}>{children}</div>}

export default function FreeMotionStudio({profile={}}){
 const canvasRef=useRef(null),fileRef=useRef(null);
 const[form,setForm]=useState({title:profile.business?`${profile.business} Ad`:"",headline:profile.business||"Your Business",subtext:profile.product||"Show your product beautifully",cta:"Message us today",duration:"10",aspectRatio:"9:16",motion:"Auto",transition:"Fade",pace:"Balanced",textPosition:"Bottom",intensity:1});
 const[media,setMedia]=useState([]),[video,setVideo]=useState(null),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const paceSeconds=useMemo(()=>form.pace==="Fast"?2.2:form.pace==="Slow"?5.2:3.5,[form.pace]);
 const estimatedScenes=useMemo(()=>Math.max(1,Math.round(Number(form.duration)/paceSeconds)),[form.duration,paceSeconds]);
 function choose(e){const files=Array.from(e.target.files||[]).slice(0,8);media.forEach(x=>URL.revokeObjectURL(x.url));setMedia(files.map(file=>({file,url:URL.createObjectURL(file),isVideo:file.type.startsWith("video/")})));setVideo(null);setError("");setStatus(files.length?`${files.length} media item${files.length===1?"":"s"} ready`:"Ready")}
 function remove(i){setMedia(items=>{const t=items[i];if(t?.url)URL.revokeObjectURL(t.url);return items.filter((_,n)=>n!==i)})}
 async function createVideo(){if(!media.length)return setError("Upload at least one photo or short clip first.");if(!window.MediaRecorder)return setError("This browser cannot export video. Try Chrome or another modern browser.");setBusy(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);const loaded=[];try{setStatus("Preparing scenes...");for(const m of media)loaded.push(m.file.type.startsWith("video/")?await videoItem(m.file):await imageItem(m.file));const[w,h]=dimensions(form.aspectRatio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=pickMime(),chunks=[];const rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_500_000}:{videoBitsPerSecond:4_500_000});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((res,rej)=>{rec.onstop=res;rec.onerror=e=>rej(e.error||new Error("Video export failed."))});rec.start(250);const totalMs=Math.max(3000,Number(form.duration)*1000),sceneCount=Math.max(loaded.length,estimatedScenes),slotMs=totalMs/sceneCount;for(let i=0;i<sceneCount;i++){const item=loaded[i%loaded.length],start=performance.now(),end=start+slotMs;if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{};while(performance.now()<end){const p=clamp((performance.now()-start)/slotMs);drawFrame(ctx,item.source,w,h,form,i,sceneCount,p);await sleep(33)}item.source.pause()}else{while(performance.now()<end){const p=clamp((performance.now()-start)/slotMs);drawFrame(ctx,item.source,w,h,form,i,sceneCount,p);await sleep(33)}}setStatus(`Rendering scene ${i+1} of ${sceneCount}...`)}rec.stop();await stopped;const out=rec.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:out}),url=URL.createObjectURL(blob),ext=out.includes("mp4")?"mp4":"webm";setVideo({url,name:`bizai-free-motion.${ext}`,size:blob.size,format:ext.toUpperCase()});setStatus(`${ext.toUpperCase()} ready · ${sceneCount} scenes rendered`)}catch(e){setError(e.message||"Could not create video.");setStatus("Stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusy(false)}}
 return <main style={{padding:"18px 18px 52px",display:"grid",gap:15,color:C.text}}>
  <section style={{...card,border:"1px solid rgba(91,216,255,.34)"}}><div style={{fontSize:10,color:C.cyan,fontWeight:900}}>FREE · ON-DEVICE RENDERER</div><h2 style={{margin:"6px 0 4px",fontSize:21}}>Free Motion Studio</h2><div style={{fontSize:12,color:C.muted,lineHeight:1.55}}>Turn your own photos and clips into a moving ad. No paid video API is used.</div></section>

  <section style={{...card,display:"grid",gap:10}}><Label>AD TEXT</Label><input style={input} value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Campaign name"/><input style={input} value={form.headline} onChange={e=>set("headline",e.target.value)} placeholder="Headline"/><input style={input} value={form.subtext} onChange={e=>set("subtext",e.target.value)} placeholder="Short supporting text"/><input style={input} value={form.cta} onChange={e=>set("cta",e.target.value)} placeholder="Call to action"/></section>

  <section style={{...card,display:"grid",gap:13}}><Label>MEDIA</Label><input ref={fileRef} type="file" accept="image/*,video/*" multiple onChange={choose} style={{display:"none"}}/><button type="button" onClick={()=>fileRef.current?.click()} style={btn}>＋ Add photos or clips</button><div style={{fontSize:10,color:C.muted}}>Up to 8 files. Short clips work best on mobile.</div>{media.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>{media.map((m,i)=><div key={m.url} style={{position:"relative",aspectRatio:"1",borderRadius:11,overflow:"hidden",border:`1px solid ${C.line}`,background:"#071329"}}>{m.isVideo?<video src={m.url} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={m.url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>}<button onClick={()=>remove(i)} style={{position:"absolute",right:3,top:3,width:24,height:24,border:0,borderRadius:8,background:"rgba(0,0,0,.65)",color:"white"}}>×</button></div>)}</div>}</section>

  <section style={{...card,display:"grid",gap:13}}><Label>MOTION PRESET</Label><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{["Auto","Push In","Pull Out","Pan","Orbit","Punchy"].map(x=><Pill key={x} active={form.motion===x} onClick={()=>set("motion",x)}>{x}</Pill>)}</div><Label>TRANSITION</Label><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{["Fade","Flash","Wipe","Cut"].map(x=><Pill key={x} active={form.transition===x} onClick={()=>set("transition",x)}>{x}</Pill>)}</div><Label>SCENE PACE</Label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{["Slow","Balanced","Fast"].map(x=><Pill key={x} active={form.pace===x} onClick={()=>set("pace",x)}>{x}</Pill>)}</div><label><Label>MOTION INTENSITY</Label><input type="range" min="0.65" max="1.35" step="0.05" value={form.intensity} onChange={e=>set("intensity",Number(e.target.value))} style={{width:"100%"}}/></label><div style={{fontSize:11,color:C.muted}}>About <b style={{color:C.text}}>{estimatedScenes} scenes</b> for this duration. BizAI repeats your media with different camera moves when needed.</div></section>

  <section style={{...card,display:"grid",gap:12}}><Label>FORMAT</Label><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{["5","10","30","60"].map(x=><Pill key={x} active={form.duration===x} onClick={()=>set("duration",x)}>{x}s</Pill>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}>{["9:16","16:9","1:1"].map(x=><Pill key={x} active={form.aspectRatio===x} onClick={()=>set("aspectRatio",x)}>{x}</Pill>)}</div><Label>TEXT POSITION</Label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}>{["Top","Center","Bottom"].map(x=><Pill key={x} active={form.textPosition===x} onClick={()=>set("textPosition",x)}>{x}</Pill>)}</div></section>

  <section style={{...card,display:"grid",gap:10}}><button onClick={createVideo} disabled={busy||!media.length} style={{...btn,opacity:busy||!media.length?.55:1,padding:"15px 14px"}}>{busy?"Rendering…":"🎬 Create cinematic video"}</button><div style={{fontSize:11,color:C.cyan,textAlign:"center",fontWeight:850}}>{status}</div>{error&&<div style={{fontSize:11,color:"#ff9aaa",padding:10,borderRadius:11,background:"rgba(255,80,100,.08)",border:"1px solid rgba(255,100,120,.22)"}}>{error}</div>}</section>

  {video&&<section style={{...card,display:"grid",gap:10}}><Label>RESULT</Label><video src={video.url} controls playsInline style={{width:"100%",borderRadius:14,background:"#000",maxHeight:560}}/><a href={video.url} download={video.name} style={{...btn,textAlign:"center",textDecoration:"none"}}>Download {video.format}</a><div style={{fontSize:10,color:C.muted,textAlign:"center"}}>{(video.size/1024/1024).toFixed(1)} MB · saved locally from your browser</div></section>}
  <canvas ref={canvasRef} style={{display:"none"}}/>
 </main>
}
