import React,{useMemo,useRef,useState}from"react";

const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#54ddff",line:"rgba(113,157,255,.22)",panel:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const input={width:"100%",boxSizing:"border-box",padding:"13px 14px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:14,outline:"none"};
const card={borderRadius:18,border:`1px solid ${C.line}`,background:C.panel,padding:15};
const btn={border:0,borderRadius:13,padding:"13px 14px",fontWeight:900,color:"white",background:"linear-gradient(135deg,#873aff,#2f79ef 55%,#20c9df)"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=p=>{p=clamp(p);return p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2};
function dims(r){if(r==="16:9")return[960,540];if(r==="1:1")return[720,720];return[540,960]}
function pickMime(){return["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}
function roundRect(ctx,x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function lines(ctx,text,maxWidth,maxLines=2){const words=String(text||"").split(/\s+/).filter(Boolean),out=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(line&&ctx.measureText(test).width>maxWidth){out.push(line);line=word;if(out.length>=maxLines-1)break}else line=test}if(line&&out.length<maxLines)out.push(line);return out}
function drawTextLines(ctx,text,x,y,maxWidth,lineHeight,maxLines=2,align="left"){ctx.textAlign=align;for(const [i,l] of lines(ctx,text,maxWidth,maxLines).entries())ctx.fillText(l,x,y+i*lineHeight);ctx.textAlign="left"}

function drawProduct(ctx,src,w,h,p,scene,fit,intensity){const sw=src.videoWidth||src.naturalWidth||src.width,sh=src.videoHeight||src.naturalHeight||src.height;if(!sw||!sh)return;const cover=Math.max(w/sw,h/sh),contain=Math.min(w/sw,h/sh),k=Number(intensity||1),e=ease(p),dir=scene%2?1:-1;
 ctx.fillStyle="#0a1730";ctx.fillRect(0,0,w,h);
 ctx.save();ctx.filter="blur(28px) brightness(.78) saturate(1.05)";const bg=cover*1.10;ctx.drawImage(src,(w-sw*bg)/2,(h-sh*bg)/2,sw*bg,sh*bg);ctx.restore();
 const base=fit==="Fill screen"?cover:contain*.94;let zoom=1,dx=0,dy=0;if(scene===0){zoom=1.01+.07*e*k;dy=.01*(1-e)}else if(scene===1){zoom=1.09-.035*e*k;dx=-.035*dir+.07*dir*e}else if(scene===2){zoom=1.03+.05*e*k;dx=.04*dir*(1-e)}else{zoom=1.02+.035*Math.sin(e*Math.PI);dy=.015*Math.sin(e*Math.PI)}
 const s=base*zoom,dw=sw*s,dh=sh*s;ctx.save();ctx.shadowColor="rgba(0,0,0,.28)";ctx.shadowBlur=18;ctx.drawImage(src,(w-dw)/2+dx*w,(h-dh)/2+dy*h,dw,dh);ctx.restore();
 const sheen=ctx.createLinearGradient((-0.3+1.5*p)*w,0,(.1+1.5*p)*w,0);sheen.addColorStop(0,"rgba(255,255,255,0)");sheen.addColorStop(.5,"rgba(255,255,255,.055)");sheen.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=sheen;ctx.fillRect(0,0,w,h)
}
function fadeOverlay(ctx,w,h,p){let a=0;if(p<.06)a=1-p/.06;else if(p>.95)a=(p-.95)/.05;if(a>0){ctx.fillStyle=`rgba(4,10,24,${a*.55})`;ctx.fillRect(0,0,w,h)}}
function bottomShade(ctx,w,h,strength=.62){const g=ctx.createLinearGradient(0,h*.58,0,h);g.addColorStop(0,"rgba(3,9,22,0)");g.addColorStop(1,`rgba(3,9,22,${strength})`);ctx.fillStyle=g;ctx.fillRect(0,h*.55,w,h*.45)}
function chip(ctx,text,x,y,w){ctx.font=`800 ${Math.round(w*.024)}px system-ui,sans-serif`;const tw=ctx.measureText(text).width,ph=w*.027,hh=w*.065;ctx.fillStyle="rgba(7,20,45,.72)";roundRect(ctx,x,y,tw+ph*2,hh,hh/2);ctx.fill();ctx.strokeStyle="rgba(103,224,255,.34)";ctx.stroke();ctx.fillStyle="#d9f9ff";ctx.fillText(text,x+ph,y+hh*.66)}
function drawHook(ctx,w,h,f,p){bottomShade(ctx,w,h,.70);const pad=w*.065;chip(ctx,"NEW",pad,pad,w);ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.070)}px system-ui,sans-serif`;drawTextLines(ctx,f.hook||f.headline||"Take a closer look",pad,h*.76,w-pad*2,w*.079,2);if(f.hookSub){ctx.font=`600 ${Math.round(w*.031)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.84)";drawTextLines(ctx,f.hookSub,pad,h*.88,w-pad*2,w*.043,1)}}
function drawProductCaption(ctx,w,h,f){if(!f.headline)return;bottomShade(ctx,w,h,.50);const pad=w*.065;ctx.fillStyle="#fff";ctx.font=`850 ${Math.round(w*.055)}px system-ui,sans-serif`;drawTextLines(ctx,f.headline,pad,h*.84,w-pad*2,w*.064,1);if(f.subtext){ctx.font=`600 ${Math.round(w*.029)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.82)";drawTextLines(ctx,f.subtext,pad,h*.91,w-pad*2,w*.04,1)}}
function drawBenefit(ctx,w,h,f){bottomShade(ctx,w,h,.64);const pad=w*.065;ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.060)}px system-ui,sans-serif`;drawTextLines(ctx,f.benefit||"Made to stand out",pad,h*.78,w-pad*2,w*.069,2);if(f.proof){ctx.font=`600 ${Math.round(w*.029)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.82)";drawTextLines(ctx,f.proof,pad,h*.91,w-pad*2,w*.04,1)}}
function drawCTA(ctx,w,h,f,p){const pad=w*.07;const g=ctx.createLinearGradient(0,h*.45,0,h);g.addColorStop(0,"rgba(2,8,21,.05)");g.addColorStop(1,"rgba(2,8,21,.78)");ctx.fillStyle=g;ctx.fillRect(0,h*.35,w,h*.65);ctx.textAlign="center";ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.062)}px system-ui,sans-serif`;drawTextLines(ctx,f.brand||f.headline||"Ready?",w/2,h*.69,w-pad*2,w*.071,1,"center");ctx.font=`600 ${Math.round(w*.030)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.84)";drawTextLines(ctx,f.ctaSub||"Ready to take the next step?",w/2,h*.77,w-pad*2,w*.043,1,"center");ctx.font=`900 ${Math.round(w*.034)}px system-ui,sans-serif`;const cta=f.cta||"Message us today",tw=ctx.measureText(cta).width,bw=Math.min(w-pad*2,tw+w*.12),bh=w*.105,x=(w-bw)/2,y=h*.83;const b=ctx.createLinearGradient(x,0,x+bw,0);b.addColorStop(0,"#8e3cff");b.addColorStop(1,"#20c9e8");ctx.fillStyle=b;roundRect(ctx,x,y,bw,bh,w*.03);ctx.fill();ctx.fillStyle="#fff";ctx.fillText(cta,w/2,y+bh*.67);ctx.textAlign="left"}
function stage(scene,total){if(scene===0)return"hook";if(scene===total-1)return"cta";if(scene===total-2&&total>3)return"benefit";return"product"}
function drawFrame(ctx,src,w,h,f,scene,total,p){drawProduct(ctx,src,w,h,p,scene,f.productFit,f.intensity);const s=stage(scene,total);if(s==="hook")drawHook(ctx,w,h,f,p);else if(s==="benefit")drawBenefit(ctx,w,h,f);else if(s==="cta")drawCTA(ctx,w,h,f,p);else if(scene===1)drawProductCaption(ctx,w,h,f);fadeOverlay(ctx,w,h,p)}
async function load(file){const url=URL.createObjectURL(file);if(file.type.startsWith("video/")){const v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=()=>j(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}const img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}
function Pill({active,onClick,children}){return <button type="button" onClick={onClick} style={{padding:"9px 10px",borderRadius:11,border:`1px solid ${active?"#64def7":C.line}`,background:active?"linear-gradient(135deg,rgba(132,58,255,.9),rgba(27,157,218,.9))":"rgba(255,255,255,.035)",color:C.text,fontWeight:850,fontSize:11}}>{children}</button>}
function Label({children}){return <div style={{fontSize:10,color:C.muted,fontWeight:900,letterSpacing:.35,marginBottom:6}}>{children}</div>}

export default function FreeMotionStudioV3({profile={}}){const canvasRef=useRef(null),fileRef=useRef(null);const[form,setForm]=useState({brand:profile.business||"",hook:profile.product?`Meet ${profile.product}`:"Take a closer look",hookSub:"Clean product-first ad",headline:profile.product||profile.business||"Your Product",subtext:profile.price?`${profile.price}`:"",benefit:"Made to stand out",proof:profile.location?`Available in ${profile.location}`:"",cta:"Message us today",ctaSub:"Ready to take the next step?",duration:"9",aspectRatio:"9:16",productFit:"Full product",intensity:1});const[media,setMedia]=useState([]),[video,setVideo]=useState(null),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");const set=(k,v)=>setForm(f=>({...f,[k]:v}));const sceneCount=useMemo(()=>Number(form.duration)<=6?4:Number(form.duration)<=12?5:6,[form.duration]);
 function choose(e){const fs=Array.from(e.target.files||[]).slice(0,8);media.forEach(x=>URL.revokeObjectURL(x.url));setMedia(fs.map(file=>({file,url:URL.createObjectURL(file),isVideo:file.type.startsWith("video/")})));setVideo(null);setError("");setStatus(fs.length?`${fs.length} media item${fs.length===1?"":"s"} ready · first item is hero product`:"Ready")}
 function remove(i){setMedia(xs=>{const t=xs[i];if(t?.url)URL.revokeObjectURL(t.url);return xs.filter((_,n)=>n!==i)})}
 function mediaIndex(scene,total,count){if(count<=1)return 0;if(scene===0||scene===total-1)return 0;return Math.min(count-1,(scene-1)%(count-1)+1)}
 async function render(){if(!media.length)return setError("Upload at least one photo or short clip first.");if(!window.MediaRecorder)return setError("This browser cannot export video. Try Chrome or another modern browser.");setBusy(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);const loaded=[];try{setStatus("Building clean product-first scenes...");for(const m of media)loaded.push(await load(m.file));const[w,h]=dims(form.aspectRatio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=pickMime(),chunks=[],rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_800_000}:{videoBitsPerSecond:4_800_000});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((r,j)=>{rec.onstop=r;rec.onerror=e=>j(e.error||new Error("Video export failed."))});rec.start(250);const totalMs=Math.max(5000,Number(form.duration)*1000),hook=Math.min(1500,totalMs*.18),cta=Math.min(1600,totalMs*.20),middle=Math.max(1800,totalMs-hook-cta),midCount=sceneCount-2,slots=[hook,...Array(midCount).fill(middle/midCount),cta];for(let i=0;i<sceneCount;i++){const item=loaded[mediaIndex(i,sceneCount,loaded.length)],start=performance.now(),end=start+slots[i];if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{}}while(performance.now()<end){drawFrame(ctx,item.source,w,h,form,i,sceneCount,clamp((performance.now()-start)/slots[i]));await sleep(33)}if(item.type==="video")item.source.pause();setStatus(`Rendering scene ${i+1} of ${sceneCount}...`)}rec.stop();await stopped;const out=rec.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:out}),url=URL.createObjectURL(blob),ext=out.includes("mp4")?"mp4":"webm";setVideo({url,name:`bizai-clean-ad.${ext}`,format:ext.toUpperCase(),size:blob.size});setStatus(`${ext.toUpperCase()} ready · clean ad V3`)}catch(e){setError(e.message||"Could not create video.");setStatus("Stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusy(false)}}
 return <main style={{padding:"18px 18px 52px",display:"grid",gap:15,color:C.text}}><section style={{...card,border:"1px solid rgba(91,216,255,.34)"}}><div style={{fontSize:10,color:C.cyan,fontWeight:900}}>CLEAN AD V3 · PRODUCT FIRST</div><h2 style={{margin:"6px 0 4px",fontSize:21}}>Cleaner, less crowded ads</h2><div style={{fontSize:12,color:C.muted,lineHeight:1.55}}>The product stays visible. Text appears only when it adds value, and the CTA waits until the ending.</div></section>
 <section style={{...card,display:"grid",gap:9}}><Label>SHORT AD COPY</Label><input style={input} value={form.hook} onChange={e=>set("hook",e.target.value)} placeholder="Opening hook"/><input style={input} value={form.headline} onChange={e=>set("headline",e.target.value)} placeholder="Product name"/><input style={input} value={form.benefit} onChange={e=>set("benefit",e.target.value)} placeholder="One benefit"/><input style={input} value={form.proof} onChange={e=>set("proof",e.target.value)} placeholder="Price, location or proof"/><input style={input} value={form.cta} onChange={e=>set("cta",e.target.value)} placeholder="CTA"/></section>
 <section style={{...card,display:"grid",gap:11}}><Label>MEDIA</Label><input ref={fileRef} type="file" accept="image/*,video/*" multiple onChange={choose} style={{display:"none"}}/><button style={btn} onClick={()=>fileRef.current?.click()}>＋ Add product photos or clips</button><div style={{fontSize:10,color:C.muted}}>Put your strongest product image first. Up to 8 files.</div>{media.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>{media.map((m,i)=><div key={m.url} style={{position:"relative",aspectRatio:"1",overflow:"hidden",borderRadius:10,border:`1px solid ${C.line}`}}>{m.isVideo?<video src={m.url} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={m.url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>}<button onClick={()=>remove(i)} style={{position:"absolute",right:3,top:3,width:23,height:23,border:0,borderRadius:7,background:"rgba(0,0,0,.65)",color:"#fff"}}>×</button></div>)}</div>}</section>
 <section style={{...card,display:"grid",gap:12}}><Label>PRODUCT FRAMING</Label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{["Full product","Fill screen"].map(x=><Pill key={x} active={form.productFit===x} onClick={()=>set("productFit",x)}>{x}</Pill>)}</div><Label>DURATION</Label><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{["6","9","12","15"].map(x=><Pill key={x} active={form.duration===x} onClick={()=>set("duration",x)}>{x}s</Pill>)}</div><Label>FORMAT</Label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}>{["9:16","16:9","1:1"].map(x=><Pill key={x} active={form.aspectRatio===x} onClick={()=>set("aspectRatio",x)}>{x}</Pill>)}</div><label><Label>MOTION</Label><input type="range" min="0.7" max="1.3" step="0.05" value={form.intensity} onChange={e=>set("intensity",Number(e.target.value))} style={{width:"100%"}}/></label></section>
 <section style={{...card,display:"grid",gap:9}}><button onClick={render} disabled={busy||!media.length} style={{...btn,opacity:busy||!media.length?.55:1,padding:"15px 14px"}}>{busy?"Rendering…":"🎬 Create clean ad"}</button><div style={{fontSize:11,color:C.cyan,textAlign:"center",fontWeight:850}}>{status}</div>{error&&<div style={{fontSize:11,color:"#ff9aaa",padding:10,borderRadius:11,background:"rgba(255,80,100,.08)",border:"1px solid rgba(255,100,120,.22)"}}>{error}</div>}</section>
 {video&&<section style={{...card,display:"grid",gap:10}}><Label>RESULT</Label><video src={video.url} controls playsInline style={{width:"100%",borderRadius:14,background:"#000",maxHeight:560}}/><a href={video.url} download={video.name} style={{...btn,textAlign:"center",textDecoration:"none"}}>Download {video.format}</a><div style={{fontSize:10,color:C.muted,textAlign:"center"}}>{(video.size/1024/1024).toFixed(1)} MB · rendered locally</div></section>}<canvas ref={canvasRef} style={{display:"none"}}/></main>}
