import React,{useMemo,useRef,useState}from"react";

const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#54ddff",purple:"#9a5cff",line:"rgba(113,157,255,.22)",panel:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const input={width:"100%",boxSizing:"border-box",padding:"13px 14px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:14,outline:"none"};
const card={borderRadius:18,border:`1px solid ${C.line}`,background:C.panel,padding:15};
const btn={border:0,borderRadius:13,padding:"12px 14px",fontWeight:900,color:"white",background:"linear-gradient(135deg,#873aff,#2f79ef 55%,#20c9df)"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=p=>{p=clamp(p);return p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2};

function dims(r){if(r==="16:9")return[960,540];if(r==="1:1")return[720,720];return[540,960]}
function rr(ctx,x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function wrap(ctx,text,x,y,max,lineH,maxLines=2,align="left"){const words=String(text||"").split(/\s+/).filter(Boolean);let lines=[],line="";for(const word of words){const t=line?line+" "+word:word;if(ctx.measureText(t).width>max&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=t}if(line&&lines.length<maxLines)lines.push(line);ctx.textAlign=align;lines.forEach((s,i)=>ctx.fillText(s,x,y+i*lineH));ctx.textAlign="left"}
function pickMime(){const list=["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"];return list.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}

function motion(p,scene,preset,intensity){const e=ease(p),k=Number(intensity||1),dir=scene%2?1:-1;if(preset==="Push In")return{z:1.02+.18*e*k,x:.025*dir*(1-e),y:.018*Math.sin(e*Math.PI)};if(preset==="Pull Out")return{z:1.20-.16*e*k,x:.025*dir*e,y:-.02+.04*e};if(preset==="Pan")return{z:1.11,x:(-.08+.16*e)*dir*k,y:.02*Math.sin(e*Math.PI)};if(preset==="Orbit")return{z:1.09+.035*Math.sin(e*Math.PI),x:.045*Math.cos(e*Math.PI*2+scene),y:.03*Math.sin(e*Math.PI*2+scene)};if(preset==="Punchy")return{z:1.04+.12*Math.sin(Math.min(1,e*1.4)*Math.PI/2)*k,x:.035*dir*(1-e),y:-.025+.05*e};const m=scene%5;if(m===0)return{z:1.03+.15*e*k,x:.03-.06*e,y:.01-.02*e};if(m===1)return{z:1.18-.13*e*k,x:-.04+.08*e,y:-.02+.04*e};if(m===2)return{z:1.10,x:-.08+.16*e,y:0};if(m===3)return{z:1.08+.05*e,x:.08-.16*e,y:.025-.05*e};return{z:1.05+.11*e,x:-.025+.05*e,y:.055-.1*e}}

function drawMedia(ctx,source,w,h,p,scene,form){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)return;const base=Math.max(w/sw,h/sh);ctx.save();ctx.filter="blur(24px) brightness(.48) saturate(.95)";const bg=base*1.18;ctx.drawImage(source,(w-sw*bg)/2,(h-sh*bg)/2,sw*bg,sh*bg);ctx.restore();const t=motion(p,scene,form.motion,form.intensity),s=base*t.z,dw=sw*s,dh=sh*s;ctx.save();ctx.translate(w/2,h/2);ctx.rotate((scene%2?1:-1)*.008*Math.sin(p*Math.PI)*Number(form.intensity||1));ctx.translate(-w/2,-h/2);ctx.drawImage(source,(w-dw)/2+t.x*w,(h-dh)/2+t.y*h,dw,dh);ctx.restore()}

function transition(ctx,w,h,p,type){const edge=.09;if(type==="Cut")return;let a=p<edge?1-p/edge:p>1-edge?(p-(1-edge))/edge:0;a=clamp(a);if(!a)return;if(type==="Flash"){ctx.fillStyle=`rgba(235,248,255,${a*.62})`;ctx.fillRect(0,0,w,h);return}if(type==="Wipe"){ctx.fillStyle=`rgba(5,12,30,${a*.82})`;const ww=w*a;ctx.fillRect(p<.5?0:w-ww,0,ww,h);return}ctx.fillStyle=`rgba(5,12,30,${a*.68})`;ctx.fillRect(0,0,w,h)}

function gradientBottom(ctx,w,h,from=.45){const g=ctx.createLinearGradient(0,h*from,0,h);g.addColorStop(0,"rgba(2,8,22,0)");g.addColorStop(1,"rgba(2,8,22,.92)");ctx.fillStyle=g;ctx.fillRect(0,h*from,w,h*(1-from))}
function pill(ctx,text,x,y,w){ctx.font=`800 ${Math.round(w*.025)}px system-ui,sans-serif`;const tw=ctx.measureText(text).width,ph=Math.round(w*.025),hh=Math.round(w*.065);ctx.fillStyle="rgba(9,28,61,.82)";rr(ctx,x,y,tw+ph*2,hh,hh/2);ctx.fill();ctx.strokeStyle="rgba(90,220,255,.45)";ctx.stroke();ctx.fillStyle="#b9f2ff";ctx.fillText(text,x+ph,y+hh*.66)}

function drawHook(ctx,w,h,form,p){gradientBottom(ctx,w,h,.34);const pad=Math.round(w*.065),lift=(1-ease(Math.min(1,p*2.2)))*Math.round(w*.06);pill(ctx,"STOP SCROLLING",pad,pad,w);ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.082)}px system-ui,sans-serif`;wrap(ctx,form.hook||form.headline||"Look at this",pad,h*.67+lift,w-pad*2,Math.round(w*.092),2);ctx.font=`650 ${Math.round(w*.035)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.9)";wrap(ctx,form.hookSub||form.subtext||"",pad,h*.84,w-pad*2,Math.round(w*.048),2)}

function drawProduct(ctx,w,h,form){gradientBottom(ctx,w,h,.45);const pad=Math.round(w*.065),pos=form.textPosition||"Bottom",anchor=pos==="Top"?h*.18:pos==="Center"?h*.51:h*.72;ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.073)}px system-ui,sans-serif`;wrap(ctx,form.headline||"Your product",pad,anchor,w-pad*2,Math.round(w*.082),2);ctx.font=`600 ${Math.round(w*.034)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.9)";wrap(ctx,form.subtext||"Made for you",pad,anchor+Math.round(w*.17),w-pad*2,Math.round(w*.046),2)}

function drawBenefit(ctx,w,h,form){gradientBottom(ctx,w,h,.40);const pad=Math.round(w*.065);pill(ctx,"WHY IT MATTERS",pad,pad,w);ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.069)}px system-ui,sans-serif`;wrap(ctx,form.benefit||form.subtext||"Built to make life easier",pad,h*.68,w-pad*2,Math.round(w*.08),2);ctx.font=`600 ${Math.round(w*.033)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.86)";wrap(ctx,form.proof||"Simple. Clear. Ready when you are.",pad,h*.84,w-pad*2,Math.round(w*.047),2)}

function drawCTA(ctx,w,h,form,p){ctx.fillStyle="rgba(3,10,26,.58)";ctx.fillRect(0,0,w,h);const centerX=w/2,pad=Math.round(w*.075);ctx.textAlign="center";ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.078)}px system-ui,sans-serif`;wrap(ctx,form.brand||form.headline||"Your Business",centerX,h*.35,w-pad*2,Math.round(w*.09),2,"center");ctx.font=`650 ${Math.round(w*.035)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.86)";wrap(ctx,form.ctaSub||"Ready to get started?",centerX,h*.53,w-pad*2,Math.round(w*.05),2,"center");ctx.font=`900 ${Math.round(w*.037)}px system-ui,sans-serif`;const cta=form.cta||"Message us today",tw=ctx.measureText(cta).width,ph=Math.round(w*.055),bh=Math.round(w*.12),bw=Math.min(w-pad*2,tw+ph*2),x=(w-bw)/2,y=h*.67;const g=ctx.createLinearGradient(x,0,x+bw,0);g.addColorStop(0,"#8d35ff");g.addColorStop(1,"#13c9ef");ctx.fillStyle=g;rr(ctx,x,y,bw,bh,Math.round(w*.035));ctx.fill();ctx.fillStyle="#fff";ctx.fillText(cta,centerX,y+bh*.68);ctx.textAlign="left";const glow=.08+.08*Math.sin(p*Math.PI);ctx.fillStyle=`rgba(96,222,255,${glow})`;ctx.fillRect(0,0,w,h)}

function stageFor(scene,total){if(scene===0)return"hook";if(scene===total-1)return"cta";const pct=scene/Math.max(1,total-1);return pct<.58?"product":"benefit"}
function drawFrame(ctx,source,w,h,form,scene,total,p){ctx.fillStyle="#071329";ctx.fillRect(0,0,w,h);drawMedia(ctx,source,w,h,p,scene,form);const stage=stageFor(scene,total);if(stage==="hook")drawHook(ctx,w,h,form,p);else if(stage==="cta")drawCTA(ctx,w,h,form,p);else if(stage==="benefit")drawBenefit(ctx,w,h,form);else drawProduct(ctx,w,h,form);ctx.fillStyle="rgba(255,255,255,.72)";ctx.font=`700 ${Math.round(w*.021)}px system-ui,sans-serif`;ctx.fillText(stage.toUpperCase(),Math.round(w*.065),h-Math.round(w*.04));transition(ctx,w,h,p,form.transition)}

async function loadImage(file){const url=URL.createObjectURL(file),img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}
async function loadVideo(file){const url=URL.createObjectURL(file),v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=()=>rej(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}
function Pill({active,onClick,children}){return <button type="button" onClick={onClick} style={{padding:"9px 11px",borderRadius:11,border:`1px solid ${active?"#64def7":C.line}`,background:active?"linear-gradient(135deg,rgba(132,58,255,.9),rgba(27,157,218,.9))":"rgba(255,255,255,.035)",color:C.text,fontWeight:850,fontSize:11}}>{children}</button>}
function Label({children}){return <div style={{fontSize:10,color:C.muted,fontWeight:900,letterSpacing:.35,marginBottom:6}}>{children}</div>}

export default function FreeMotionStudioV2({profile={}}){
 const canvasRef=useRef(null),fileRef=useRef(null);
 const[form,setForm]=useState({brand:profile.business||"",title:profile.business?`${profile.business} Ad`:"",hook:profile.product?`Still looking for the right ${profile.product}?`:"Stop scrolling — see this",hookSub:"A quick look at what makes this worth your attention",headline:profile.product||profile.business||"Your Product",subtext:profile.price?`Available for ${profile.price}`:"Made to stand out",benefit:"Why customers should care about this",proof:profile.location?`Available in ${profile.location}`:"Simple. Useful. Easy to get.",cta:"Message us today",ctaSub:"Ready to take the next step?",duration:"10",aspectRatio:"9:16",motion:"Auto",transition:"Fade",pace:"Balanced",textPosition:"Bottom",intensity:1});
 const[media,setMedia]=useState([]),[video,setVideo]=useState(null),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const paceSeconds=useMemo(()=>form.pace==="Fast"?2.0:form.pace==="Slow"?4.8:3.2,[form.pace]);
 const estimatedScenes=useMemo(()=>Math.max(4,Math.round(Number(form.duration)/paceSeconds)),[form.duration,paceSeconds]);
 function choose(e){const files=Array.from(e.target.files||[]).slice(0,8);media.forEach(x=>URL.revokeObjectURL(x.url));setMedia(files.map(file=>({file,url:URL.createObjectURL(file),isVideo:file.type.startsWith("video/")})));setVideo(null);setError("");setStatus(files.length?`${files.length} media item${files.length===1?"":"s"} ready · first item is the hero product scene`:"Ready")}
 function remove(i){setMedia(items=>{const t=items[i];if(t?.url)URL.revokeObjectURL(t.url);return items.filter((_,n)=>n!==i)})}
 function orderedIndex(scene,total,count){if(count<=1)return 0;if(scene===0||scene===total-1)return 0;if(scene===1)return 0;return 1+((scene-2)%(count-1))}
 async function createVideo(){if(!media.length)return setError("Upload at least one photo or short clip first.");if(!window.MediaRecorder)return setError("This browser cannot export video. Try Chrome or another modern browser.");setBusy(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);const loaded=[];try{setStatus("Planning Hook → Product → Benefit → CTA...");for(const m of media)loaded.push(m.file.type.startsWith("video/")?await loadVideo(m.file):await loadImage(m.file));const[w,h]=dims(form.aspectRatio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=pickMime(),chunks=[];const rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_700_000}:{videoBitsPerSecond:4_700_000});rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((res,rej)=>{rec.onstop=res;rec.onerror=e=>rej(e.error||new Error("Video export failed."))});rec.start(250);const totalMs=Math.max(5000,Number(form.duration)*1000),sceneCount=estimatedScenes,hookMs=Math.min(2000,totalMs*.24),ctaMs=Math.min(1800,totalMs*.22),middleMs=Math.max(1200,totalMs-hookMs-ctaMs),middleCount=Math.max(2,sceneCount-2),slots=[hookMs,...Array(middleCount).fill(middleMs/middleCount),ctaMs];for(let i=0;i<slots.length;i++){const item=loaded[orderedIndex(i,slots.length,loaded.length)],slotMs=slots[i],start=performance.now(),end=start+slotMs;if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{};while(performance.now()<end){const p=clamp((performance.now()-start)/slotMs);drawFrame(ctx,item.source,w,h,form,i,slots.length,p);await sleep(33)}item.source.pause()}else{while(performance.now()<end){const p=clamp((performance.now()-start)/slotMs);drawFrame(ctx,item.source,w,h,form,i,slots.length,p);await sleep(33)}}setStatus(`Rendering ${stageFor(i,slots.length)} scene ${i+1}/${slots.length}...`)}rec.stop();await stopped;const out=rec.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:out}),url=URL.createObjectURL(blob),ext=out.includes("mp4")?"mp4":"webm";setVideo({url,name:`bizai-conversion-ad.${ext}`,size:blob.size,format:ext.toUpperCase()});setStatus(`${ext.toUpperCase()} ready · Hook → Product → Benefit → CTA applied`)}catch(e){setError(e.message||"Could not create video.");setStatus("Stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusy(false)}}
 return <main style={{padding:"18px 18px 52px",display:"grid",gap:15,color:C.text}}>
  <section style={{...card,border:"1px solid rgba(91,216,255,.34)"}}><div style={{fontSize:10,color:C.cyan,fontWeight:900}}>ENHANCED · CONVERSION STRUCTURE</div><h2 style={{margin:"6px 0 4px",fontSize:21}}>Free Motion Studio</h2><div style={{fontSize:12,color:C.muted,lineHeight:1.55}}>BizAI now structures every free ad as Hook → Product → Benefit → CTA. The first media item is treated as your hero product.</div></section>

  <section style={{...card,display:"grid",gap:10}}><Label>HOOK · FIRST ~2 SECONDS</Label><input style={input} value={form.hook} onChange={e=>set("hook",e.target.value)} placeholder="Stop-scrolling hook"/><input style={input} value={form.hookSub} onChange={e=>set("hookSub",e.target.value)} placeholder="Short hook support line"/><Label>PRODUCT & BENEFIT</Label><input style={input} value={form.headline} onChange={e=>set("headline",e.target.value)} placeholder="Product headline"/><input style={input} value={form.subtext} onChange={e=>set("subtext",e.target.value)} placeholder="Product detail or price"/><input style={input} value={form.benefit} onChange={e=>set("benefit",e.target.value)} placeholder="Main customer benefit"/><input style={input} value={form.proof} onChange={e=>set("proof",e.target.value)} placeholder="Proof, location, feature, or trust point"/><Label>PROFESSIONAL ENDING</Label><input style={input} value={form.brand} onChange={e=>set("brand",e.target.value)} placeholder="Brand/business name"/><input style={input} value={form.ctaSub} onChange={e=>set("ctaSub",e.target.value)} placeholder="Closing line"/><input style={input} value={form.cta} onChange={e=>set("cta",e.target.value)} placeholder="Call to action"/></section>

  <section style={{...card,display:"grid",gap:13}}><Label>MEDIA · PRODUCT FIRST</Label><input ref={fileRef} type="file" accept="image/*,video/*" multiple onChange={choose} style={{display:"none"}}/><button type="button" onClick={()=>fileRef.current?.click()} style={btn}>＋ Add photos or clips</button><div style={{fontSize:10,color:C.muted}}>Put your best product photo/video first. BizAI reuses it for the hook and final CTA, then rotates the rest through product/benefit scenes.</div>{media.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>{media.map((m,i)=><div key={m.url} style={{position:"relative",aspectRatio:"1",borderRadius:11,overflow:"hidden",border:`1px solid ${i===0?"#64def7":C.line}`,background:"#071329"}}>{m.isVideo?<video src={m.url} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={m.url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>}{i===0&&<div style={{position:"absolute",left:4,bottom:4,padding:"3px 6px",borderRadius:7,background:"rgba(0,0,0,.7)",fontSize:8,fontWeight:900,color:C.cyan}}>HERO</div>}<button onClick={()=>remove(i)} style={{position:"absolute",right:3,top:3,width:24,height:24,border:0,borderRadius:8,background:"rgba(0,0,0,.65)",color:"white"}}>×</button></div>)}</div>}</section>

  <section style={{...card,display:"grid",gap:13}}><Label>MOTION PRESET</Label><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{["Auto","Push In","Pull Out","Pan","Orbit","Punchy"].map(x=><Pill key={x} active={form.motion===x} onClick={()=>set("motion",x)}>{x}</Pill>)}</div><Label>TRANSITION</Label><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{["Fade","Flash","Wipe","Cut"].map(x=><Pill key={x} active={form.transition===x} onClick={()=>set("transition",x)}>{x}</Pill>)}</div><Label>SCENE PACE</Label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{["Slow","Balanced","Fast"].map(x=><Pill key={x} active={form.pace===x} onClick={()=>set("pace",x)}>{x}</Pill>)}</div><label><Label>MOTION INTENSITY</Label><input type="range" min="0.65" max="1.35" step="0.05" value={form.intensity} onChange={e=>set("intensity",Number(e.target.value))} style={{width:"100%"}}/></label></section>

  <section style={{...card,display:"grid",gap:12}}><Label>FORMAT</Label><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{["5","10","30","60"].map(x=><Pill key={x} active={form.duration===x} onClick={()=>set("duration",x)}>{x}s</Pill>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}>{["9:16","16:9","1:1"].map(x=><Pill key={x} active={form.aspectRatio===x} onClick={()=>set("aspectRatio",x)}>{x}</Pill>)}</div><Label>PRODUCT TEXT POSITION</Label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}>{["Top","Center","Bottom"].map(x=><Pill key={x} active={form.textPosition===x} onClick={()=>set("textPosition",x)}>{x}</Pill>)}</div><div style={{fontSize:10,color:C.muted}}>Estimated structure: 1 hook + {Math.max(2,estimatedScenes-2)} product/benefit scenes + 1 dedicated CTA ending.</div></section>

  <section style={{...card,display:"grid",gap:10}}><button onClick={createVideo} disabled={busy||!media.length} style={{...btn,opacity:busy||!media.length?.55:1,padding:"15px 14px"}}>{busy?"Rendering structured ad…":"🎯 Create conversion-focused ad"}</button><div style={{fontSize:11,color:C.cyan,textAlign:"center",fontWeight:850}}>{status}</div>{error&&<div style={{fontSize:11,color:"#ff9aaa",padding:10,borderRadius:11,background:"rgba(255,80,100,.08)",border:"1px solid rgba(255,100,120,.22)"}}>{error}</div>}</section>

  {video&&<section style={{...card,display:"grid",gap:10}}><Label>RESULT</Label><video src={video.url} controls playsInline style={{width:"100%",borderRadius:14,background:"#000",maxHeight:560}}/><a href={video.url} download={video.name} style={{...btn,textAlign:"center",textDecoration:"none"}}>Download {video.format}</a><div style={{fontSize:10,color:C.muted,textAlign:"center"}}>{(video.size/1024/1024).toFixed(1)} MB · rendered locally on your device</div></section>}
  <canvas ref={canvasRef} style={{display:"none"}}/>
 </main>
}
