import React,{useEffect,useMemo,useState}from"react";

const API=(import.meta.env.VITE_VIDEO_API_URL||"https://bizai-video-dev.onrender.com").replace(/\/$/,"");
const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#50d9ff",purple:"#9258ff",line:"rgba(115,157,255,.22)",card:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const input={width:"100%",boxSizing:"border-box",padding:"13px 14px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:14,outline:"none"};
const card={border:`1px solid ${C.line}`,borderRadius:18,background:C.card,padding:15};
const button={width:"100%",padding:"13px 15px",border:0,borderRadius:14,background:"linear-gradient(135deg,#8538ff,#357cff 55%,#19c8ea)",color:"white",fontWeight:900,fontSize:14};

async function request(path,options={}){const r=await fetch(`${API}${path}`,{credentials:"include",...options,headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||`Request failed (${r.status})`);e.data=d;throw e}return d}
function money(n){return `$${Number(n||0).toFixed(2)}`}
function jobVideoUrl(job){return job?.videoUrl?`${API}${job.videoUrl}`:null}

export default function VeoVideoStudio(){
 const[health,setHealth]=useState(null),[user,setUser]=useState(null),[authMode,setAuthMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authBusy,setAuthBusy]=useState(false);
 const[prompt,setPrompt]=useState(""),[improved,setImproved]=useState(""),[useImproved,setUseImproved]=useState(false),[reference,setReference]=useState(null),[quality,setQuality]=useState("fast"),[ratio,setRatio]=useState("9:16"),[duration,setDuration]=useState(8),[resolution,setResolution]=useState("720p");
 const[review,setReview]=useState(null),[job,setJob]=useState(null),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const activePrompt=useImproved&&improved.trim()?improved.trim():prompt.trim();
 const model=health?.models?.[quality];
 const localEstimate=useMemo(()=>model?Number((Number(model.rates?.[resolution]||0)*Number(duration)).toFixed(2)):0,[model,resolution,duration]);
 const setupReady=Boolean(health?.providerConfigured&&health?.databaseReady&&health?.authConfigured);

 useEffect(()=>{(async()=>{try{const h=await request("/health");setHealth(h);if(h.authConfigured){try{const me=await request("/api/auth/me");setUser(me.user)}catch{}}}catch(e){setError(e.message)}})()},[]);
 useEffect(()=>{if(reference&&duration!==8)setDuration(8)},[reference]);
 useEffect(()=>{if((resolution==="1080p"||resolution==="4k")&&duration!==8)setDuration(8)},[resolution]);
 useEffect(()=>{setReview(null)},[prompt,improved,useImproved,reference,quality,ratio,duration,resolution]);
 useEffect(()=>{if(user)loadHistory()},[user]);
 useEffect(()=>{if(!job||!["QUEUED","RUNNING"].includes(job.status))return;const t=setInterval(async()=>{try{const d=await request(`/api/video/jobs/${job.id}`);setJob(d.job);if(!["QUEUED","RUNNING"].includes(d.job.status)){clearInterval(t);loadHistory()}}catch(e){setError(e.message)}},5000);return()=>clearInterval(t)},[job?.id,job?.status]);

 async function auth(){setAuthBusy(true);setError("");try{const d=await request(`/api/auth/${authMode}`,{method:"POST",body:JSON.stringify({email,password})});setUser(d.user);setPassword("");}catch(e){setError(e.message)}finally{setAuthBusy(false)}}
 async function logout(){await request("/api/auth/logout",{method:"POST"});setUser(null);setHistory([]);setJob(null)}
 async function improve(){if(!prompt.trim())return setError("Write your video prompt first.");setBusy(true);setError("");try{const d=await request("/api/video/improve-prompt",{method:"POST",headers:{"x-bizai-csrf":"1"},body:JSON.stringify({prompt})});setImproved(d.improvedPrompt);setUseImproved(true);setMessage("Improved prompt ready — review it before generating.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function reviewCost(){if(!activePrompt)return setError("Write a prompt first.");if(!user)return setError("Sign in before starting a paid Veo generation.");setBusy(true);setError("");try{const d=await request("/api/video/estimate",{method:"POST",body:JSON.stringify({quality,aspectRatio:ratio,duration,resolution,hasReference:Boolean(reference)})});setReview({...d,idempotencyKey:crypto.randomUUID()})}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function generate(){if(!review)return;setBusy(true);setError("");setMessage("Submitting one paid Veo job…");try{const f=new FormData();f.append("prompt",activePrompt);f.append("quality",quality);f.append("aspectRatio",ratio);f.append("duration",String(duration));f.append("resolution",resolution);f.append("idempotencyKey",review.idempotencyKey);f.append("confirmedCostUsd",String(review.estimatedCostUsd));if(reference)f.append("referenceImage",reference);const d=await request("/api/video/start",{method:"POST",headers:{"x-bizai-csrf":"1"},body:f});setJob(d.job);setReview(null);setMessage(d.duplicate?"Existing request recovered — no duplicate paid submission was made.":"Veo job accepted. Generation is asynchronous; this page will keep checking its real status.");await loadHistory()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function loadHistory(){try{const d=await request("/api/video/jobs");setHistory(d.jobs||[])}catch(e){if(e.message!=="Sign in to continue.")setError(e.message)}}
 async function download(job){try{const r=await fetch(jobVideoUrl(job)+"?download=1",{credentials:"include"});if(!r.ok)throw new Error("Could not download stored video.");const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`bizai-veo-${job.id}.mp4`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e.message)}}

 const forced8=Boolean(reference)||resolution!=="720p";
 return <main style={{padding:"18px 18px 50px",display:"grid",gap:15,color:C.text}}>
  <section style={{...card,border:"1px solid rgba(93,215,255,.35)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><div style={{fontSize:11,color:C.cyan,fontWeight:900}}>REAL AI VIDEO · GOOGLE VEO 3.1</div><h2 style={{margin:"7px 0 4px",fontSize:22}}>Create Video</h2><div style={{fontSize:12,color:C.muted,lineHeight:1.5}}>Short clips first. Real Veo generation, native audio, honest job status and private history.</div></div><div style={{fontSize:10,padding:"6px 9px",borderRadius:999,border:`1px solid ${setupReady?"#39d98a":"#ffb34d"}`,color:setupReady?"#80f1b5":"#ffd28a"}}>{setupReady?"READY":"SETUP"}</div></div></section>

  {health&&!setupReady&&<section style={{...card,border:"1px solid rgba(255,177,72,.35)"}}><div style={{fontWeight:900,color:"#ffd28a",marginBottom:7}}>Setup required before paid Veo generation</div><div style={{fontSize:12,color:C.muted,lineHeight:1.6}}>Backend found: {health.provider}. Add <b style={{color:C.text}}>GEMINI_API_KEY</b>, <b style={{color:C.text}}>DATABASE_URL</b>, and a long <b style={{color:C.text}}>JWT_SECRET</b> to the <b style={{color:C.text}}>bizai-video-dev</b> Render service. Google Veo is not available on the Gemini API free tier, so the Google project/API key must have paid billing enabled. Do not put these secrets in the frontend or in chat.</div><div style={{fontSize:11,color:"#b9c9e5",marginTop:9}}>Provider key: {health.providerConfigured?"configured":"missing"} · Database: {health.databaseReady?"ready":"missing/not connected"} · Auth: {health.authConfigured?"configured":"missing"}</div></section>}

  {health?.authConfigured&&!user&&<section style={card}><div style={{fontWeight:900,marginBottom:10}}>{authMode==="login"?"Sign in":"Create video account"}</div><div style={{display:"grid",gap:9}}><input style={input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input style={input} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" type="password"/><button style={button} disabled={authBusy} onClick={auth}>{authBusy?"Please wait…":authMode==="login"?"Sign in":"Create account"}</button><button onClick={()=>setAuthMode(authMode==="login"?"register":"login")} style={{background:"none",border:0,color:C.cyan,fontWeight:800}}>{authMode==="login"?"New here? Create account":"Already have an account? Sign in"}</button></div></section>}
  {user&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:11,color:C.muted}}><span>Private account: {user.email}</span><button onClick={logout} style={{background:"none",border:0,color:C.cyan,fontWeight:800}}>Sign out</button></div>}

  <section style={{...card,display:"grid",gap:12}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>1 · DESCRIBE THE CLIP</div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="Example: Cinematic close-up of a white iPhone 13 on a dark glass table. A young creator picks it up and uses the camera at golden hour. Slow dolly-in, realistic reflections, premium commercial lighting, natural city ambience and subtle music." style={{...input,resize:"vertical",lineHeight:1.5,minHeight:150}}/><button onClick={improve} disabled={!user||busy||!health?.providerConfigured} style={{...button,background:"linear-gradient(135deg,#6436bc,#245da9)",opacity:(!user||busy||!health?.providerConfigured)?.55:1}}>✨ Improve Prompt</button>{improved&&<div style={{display:"grid",gap:8}}><div style={{fontSize:11,color:"#b9c9e5"}}>Review the improved prompt. You can edit it before deciding whether to use it.</div><textarea value={improved} onChange={e=>setImproved(e.target.value)} rows={7} style={{...input,resize:"vertical",lineHeight:1.5}}/><label style={{fontSize:12,color:C.text,display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={useImproved} onChange={e=>setUseImproved(e.target.checked)}/> Use improved prompt for generation</label></div>}</section>

  <section style={{...card,display:"grid",gap:13}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>2 · MODEL & SUPPORTED CONTROLS</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{["fast","premium"].map(q=><button key={q} onClick={()=>setQuality(q)} style={{padding:13,borderRadius:13,border:`1px solid ${quality===q?"#62dfff":C.line}`,background:quality===q?"linear-gradient(135deg,#7440e8,#187cd1)":"rgba(255,255,255,.035)",color:C.text,fontWeight:900}}>{q==="fast"?"⚡ Fast":"✦ Premium"}<div style={{fontSize:9,opacity:.75,marginTop:3}}>{health?.models?.[q]?.id||"Veo 3.1"}</div></button>)}</div><label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>REFERENCE IMAGE · OPTIONAL</div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setReference(e.target.files?.[0]||null)} style={{...input,padding:10}}/><div style={{fontSize:10,color:C.muted,marginTop:5}}>One JPG/PNG/WebP, max 10MB. A reference image forces an 8-second clip.</div></label>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>ASPECT RATIO</div><select value={ratio} onChange={e=>setRatio(e.target.value)} style={input}><option value="9:16">9:16 Vertical</option><option value="16:9">16:9 Landscape</option></select></label><label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>RESOLUTION</div><select value={resolution} onChange={e=>setResolution(e.target.value)} style={input}><option value="720p">720p</option><option value="1080p">1080p</option><option value="4k">4K</option></select></label></div>
   <label><div style={{fontSize:10,color:C.muted,fontWeight:900,marginBottom:5}}>DURATION</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{[4,6,8].map(d=><button key={d} disabled={forced8&&d!==8} onClick={()=>setDuration(d)} style={{padding:11,borderRadius:12,border:`1px solid ${duration===d?"#62dfff":C.line}`,background:duration===d?"rgba(64,139,255,.28)":"rgba(255,255,255,.03)",color:forced8&&d!==8?"#536683":C.text,fontWeight:850}}>{d}s</button>)}</div>{forced8&&<div style={{fontSize:10,color:"#ffd28a",marginTop:6}}>{reference?"Reference-image generation":"1080p/4K"} is supported only at 8 seconds.</div>}</label>
   <div style={{fontSize:12,color:"#c7d5ec",lineHeight:1.55}}>Estimated Google list price: <b style={{color:"#fff"}}>{money(localEstimate)}</b> · Audio is generated by Veo and is always on. No automatic model upgrades or regenerations.</div><button onClick={reviewCost} disabled={!user||busy||!health?.providerConfigured} style={{...button,opacity:(!user||busy||!health?.providerConfigured)?.55:1}}>Review cost before generation</button>
  </section>

  {review&&<section style={{...card,border:"1px solid rgba(255,189,84,.45)"}}><div style={{fontWeight:900,color:"#ffd28a"}}>Paid generation confirmation</div><div style={{fontSize:12,color:C.muted,lineHeight:1.6,margin:"8px 0 12px"}}>One {duration}s {resolution} {quality} Veo clip. Estimated provider cost: <b style={{color:"#fff"}}>{money(review.estimatedCostUsd)}</b>. This submits exactly one paid request. BizAI will not retry it automatically or switch to a more expensive model.</div><button onClick={generate} disabled={busy} style={button}>{busy?"Submitting…":`Confirm & generate for ${money(review.estimatedCostUsd)}`}</button></section>}

  {message&&<div style={{fontSize:12,color:C.cyan,textAlign:"center",fontWeight:800}}>{message}</div>}{error&&<div style={{padding:12,borderRadius:13,border:"1px solid rgba(255,100,120,.28)",background:"rgba(255,80,100,.08)",color:"#ffc3cc",fontSize:12,lineHeight:1.5}}>{error}</div>}

  {job&&<section style={{...card,display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between"}}><b>Current generation</b><span style={{fontSize:11,color:C.cyan,fontWeight:900}}>{job.status}</span></div><div style={{fontSize:11,color:C.muted,lineHeight:1.5}}>{job.status==="QUEUED"?"Google accepted the job; waiting for Veo compute.":job.status==="RUNNING"?"Veo is generating the clip now.":job.status==="COMPLETED"?"Generation finished and the MP4 was copied into BizAI durable storage.":job.status==="FAILED"?(job.error||"Generation failed."):"Preparing job…"}</div>{job.status==="COMPLETED"&&<><video src={jobVideoUrl(job)} crossOrigin="use-credentials" controls playsInline style={{width:"100%",borderRadius:14,background:"#000"}}/><button style={button} onClick={()=>download(job)}>Download MP4</button></>}</section>}

  {user&&<section style={{...card,display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>Private generation history</b><button onClick={loadHistory} style={{background:"none",border:0,color:C.cyan,fontWeight:800}}>Refresh</button></div>{history.length===0?<div style={{fontSize:11,color:C.muted}}>No Veo generations yet.</div>:history.map(h=><div key={h.id} style={{padding:"10px 0",borderTop:`1px solid ${C.line}`}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><span style={{fontSize:12,fontWeight:850}}>{h.quality} · {h.duration}s · {h.resolution}</span><span style={{fontSize:10,color:h.status==="COMPLETED"?"#81efb6":C.cyan}}>{h.status}</span></div><div style={{fontSize:10,color:C.muted,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",marginTop:4}}>{h.prompt}</div>{h.status==="COMPLETED"&&<button onClick={()=>download(h)} style={{marginTop:6,background:"none",border:0,color:C.cyan,fontWeight:800,padding:0}}>Download stored MP4</button>}</div>)}</section>}

  <div style={{fontSize:10,color:C.muted,lineHeight:1.55,textAlign:"center"}}>Veo 3.1 currently supports short 4s, 6s and 8s clips. Longer multi-scene editing is deliberately not included in this first version.</div>
 </main>;
}
