import React,{useMemo,useRef,useState}from"react";

const AI_API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
const C={text:"#f7f9ff",muted:"#91a5ca",cyan:"#54ddff",purple:"#9a5cff",line:"rgba(113,157,255,.22)",panel:"linear-gradient(145deg,rgba(10,37,76,.98),rgba(5,23,52,.98))"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

const inputStyle={width:"100%",boxSizing:"border-box",padding:"14px 16px",borderRadius:14,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.045)",color:C.text,fontSize:15,outline:"none"};
const cardStyle={borderRadius:18,border:`1px solid ${C.line}`,background:C.panel,boxShadow:"inset 0 1px 0 rgba(255,255,255,.025)"};

async function jsonFetch(url,options){const r=await fetch(url,options);let d;try{d=await r.json()}catch{throw new Error("The server returned an invalid response.")}if(!r.ok)throw new Error(d?.error||"Request failed.");return d}
function pickRecorderMime(){const candidates=["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"];return candidates.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}
function dimensions(ratio){if(ratio==="16:9")return[960,540];if(ratio==="1:1")return[720,720];return[540,960]}
function drawCover(ctx,source,w,h){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)return;const scale=Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(source,(w-dw)/2,(h-dh)/2,dw,dh)}
function roundedRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=3){const words=String(text||"").split(/\s+/).filter(Boolean);let line="",lines=[];for(const word of words){const t=line?`${line} ${word}`:word;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=t}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight))}
function drawFrame(ctx,source,w,h,form,index,total){ctx.fillStyle="#071329";ctx.fillRect(0,0,w,h);drawCover(ctx,source,w,h);const g=ctx.createLinearGradient(0,h*.4,0,h);g.addColorStop(0,"rgba(2,8,22,0)");g.addColorStop(1,"rgba(2,8,22,.9)");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const pad=Math.round(w*.065);ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.075)}px system-ui,sans-serif`;wrapText(ctx,form.headline||form.title||"Your Ad",pad,h*.72,w-pad*2,Math.round(w*.085),2);ctx.font=`600 ${Math.round(w*.036)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.9)";wrapText(ctx,form.subtext||form.goal||"",pad,h*.84,w-pad*2,Math.round(w*.05),2);const cta=form.cta||"Message us today";ctx.font=`800 ${Math.round(w*.035)}px system-ui,sans-serif`;const tw=ctx.measureText(cta).width,ph=Math.round(w*.045),pv=Math.round(w*.026),boxH=pv*2+Math.round(w*.05),boxY=h-pad-boxH;const grd=ctx.createLinearGradient(pad,0,pad+Math.min(w-pad*2,tw+ph*2),0);grd.addColorStop(0,"#8d35ff");grd.addColorStop(1,"#13c9ef");ctx.fillStyle=grd;roundedRect(ctx,pad,boxY,Math.min(w-pad*2,tw+ph*2),boxH,Math.round(w*.03));ctx.fill();ctx.fillStyle="#fff";ctx.fillText(cta,pad+ph,h-pad-pv);ctx.fillStyle="rgba(255,255,255,.78)";ctx.font=`700 ${Math.round(w*.024)}px system-ui,sans-serif`;ctx.fillText(`${index+1}/${total}`,w-pad-Math.round(w*.07),pad+Math.round(w*.03))}
async function imageFromFile(file){const url=URL.createObjectURL(file);const img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}
async function videoFromFile(file){const url=URL.createObjectURL(file);const v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=()=>reject(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}

function SectionLabel({icon,children}){return <div style={{display:"flex",gap:8,alignItems:"center",fontSize:11,fontWeight:900,color:"#a9b9d9",letterSpacing:.3,textTransform:"uppercase",marginBottom:7}}><span style={{fontSize:15,color:C.purple}}>{icon}</span>{children}</div>}
function ChoiceSelect({icon,label,value,onChange,options}){return <label style={{display:"block"}}><SectionLabel icon={icon}>{label}</SectionLabel><div style={{position:"relative"}}><select value={value} onChange={e=>onChange(e.target.value)} style={{...inputStyle,appearance:"none",paddingLeft:44,paddingRight:42}}>{options.map(o=><option key={o}>{o}</option>)}</select><span style={{position:"absolute",left:14,top:"50%",transform:"translateY(-50%)",fontSize:20}}>{icon}</span><span style={{position:"absolute",right:15,top:"50%",transform:"translateY(-52%)",fontSize:17,color:"#a9b9d9",pointerEvents:"none"}}>⌄</span></div></label>}

export default function VideoAdStudioV2({profile={}}){
 const canvasRef=useRef(null),fileRef=useRef(null);
 const[form,setForm]=useState({title:profile.business?`${profile.business} Video Ad`:"",instructions:"",audience:"Men",goal:"WhatsApp",platform:"TikTok / Instagram Reels",duration:"60",tone:"Energetic",aspectRatio:"9:16",headline:profile.business||"ASD",subtext:profile.product||"Yes",cta:"Message us today"});
 const[media,setMedia]=useState([]),[plan,setPlan]=useState(""),[guideOpen,setGuideOpen]=useState(false),[video,setVideo]=useState(null),[busyPlan,setBusyPlan]=useState(false),[busyVideo,setBusyVideo]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const activeGlow={background:"linear-gradient(135deg,#933cff,#27c9ff)",border:"1px solid #6fe1ff",boxShadow:"0 0 0 2px rgba(137,63,255,.32),0 0 18px rgba(49,198,255,.35)",color:"#fff"};
 const previewItems=useMemo(()=>media, [media]);

 function chooseMedia(e){const picked=Array.from(e.target.files||[]).slice(0,8);media.forEach(x=>URL.revokeObjectURL(x.url));const next=picked.map(file=>({file,url:URL.createObjectURL(file),isVideo:file.type.startsWith("video/")}));setMedia(next);setVideo(null);setError("");setStatus(next.length?`${next.length} media item${next.length===1?"":"s"} ready`:"Ready")}
 function removeMedia(index){setMedia(items=>{const target=items[index];if(target?.url)URL.revokeObjectURL(target.url);const next=items.filter((_,i)=>i!==index);setStatus(next.length?`${next.length} media item${next.length===1?"":"s"} ready`:"Ready");return next})}

 async function suggestWithAI(){setBusyPlan(true);setError("");setStatus("BizAI is suggesting ad text...");try{const d=await jsonFetch(`${AI_API}/api/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"video-ad",businessName:profile.business,product:profile.product,price:profile.price,location:profile.location,title:form.title,instructions:form.instructions||`Create concise on-screen ad text for ${form.platform}.`,audience:form.audience,goal:form.goal,platform:form.platform,duration:`${form.duration} seconds`,tone:form.tone})});const text=String(d.text||"").trim();setPlan(text);const lines=text.split(/\n+/).map(x=>x.replace(/^[-*#\d.\s]+/,"").trim()).filter(Boolean);setForm(f=>({...f,headline:f.headline||profile.business||lines[0]||"Your Business",subtext:lines.find(x=>x.length>8&&x.length<80)||f.subtext||profile.product||"Made for you",cta:f.cta||"Message us today"}));setStatus(d.mode==="lite"?"Suggestions ready · Lite mode":"Suggestions ready")}catch(e){setError(e.message);setStatus("Suggestions stopped")}finally{setBusyPlan(false)}}

 async function createFreeVideo(){if(!media.length){setError("Upload at least one photo or short video first.");return}if(!window.MediaRecorder){setError("This browser cannot export video yet. Try Chrome, Safari, or another modern browser.");return}setBusyVideo(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);setStatus("Preparing your free video...");const loaded=[];try{for(const item of media)loaded.push(item.file.type.startsWith("video/")?await videoFromFile(item.file):await imageFromFile(item.file));const[w,h]=dimensions(form.aspectRatio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=pickRecorderMime(),chunks=[];const recorder=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_000_000}:{videoBitsPerSecond:4_000_000});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||new Error("Video export failed."))});recorder.start(250);const totalMs=Math.max(3000,Number(form.duration||10)*1000),slotMs=Math.max(900,totalMs/loaded.length);for(let i=0;i<loaded.length;i++){const item=loaded[i],endAt=performance.now()+slotMs;if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{};while(performance.now()<endAt){drawFrame(ctx,item.source,w,h,form,i,loaded.length);await sleep(33)}item.source.pause()}else{while(performance.now()<endAt){drawFrame(ctx,item.source,w,h,form,i,loaded.length);await sleep(33)}}setStatus(`Rendering scene ${i+1} of ${loaded.length}...`)}recorder.stop();await stopped;const outMime=recorder.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:outMime}),url=URL.createObjectURL(blob),ext=outMime.includes("mp4")?"mp4":"webm";setVideo({url,fileName:`bizai-${(form.title||"video-ad").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"video-ad"}.${ext}`,format:ext.toUpperCase(),size:blob.size});setStatus(`${ext.toUpperCase()} video ready · no paid AI used`)}catch(e){setError(e.message||"Could not create the video.");setStatus("Video creation stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusyVideo(false)}}

 const durationButtons=["5","10","30","60"],ratios=[{v:"9:16",icon:"▯",name:"Vertical"},{v:"16:9",icon:"▭",name:"Horizontal"},{v:"1:1",icon:"□",name:"Square"}];
 return <main style={{padding:"18px 18px 48px",display:"flex",flexDirection:"column",gap:16,color:C.text,background:"radial-gradient(circle at 50% 0%,rgba(24,82,150,.10),transparent 35%)"}}>
  <div style={{display:"flex",justifyContent:"flex-end"}}><button type="button" onClick={()=>setGuideOpen(v=>!v)} style={{padding:"9px 14px",borderRadius:12,border:"1px solid #3d7fff",background:"rgba(13,41,83,.92)",color:"#fff",fontWeight:850,fontSize:12,boxShadow:"0 0 14px rgba(53,122,255,.28)"}}>💡 Guide</button></div>

  {guideOpen&&<section style={{...cardStyle,padding:14,display:"grid",gap:10}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>CREATIVE GUIDE</div><input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Campaign name" style={inputStyle}/><textarea rows={4} value={form.instructions} onChange={e=>set("instructions",e.target.value)} placeholder="Describe the ad you want, the key scenes, offer, and final message." style={{...inputStyle,resize:"vertical",lineHeight:1.45}}/>{plan&&<div style={{fontSize:12,color:"#cbd8ef",lineHeight:1.55,whiteSpace:"pre-wrap",background:"rgba(255,255,255,.035)",padding:10,borderRadius:12}}>{plan}</div>}</section>}

  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
   <ChoiceSelect icon="👥" label="Target audience" value={form.audience} onChange={v=>set("audience",v)} options={["Men","Women","Everyone","Businesses"]}/>
   <ChoiceSelect icon="🎯" label="Goal" value={form.goal} onChange={v=>set("goal",v)} options={["WhatsApp","Sales","Website visits","Brand awareness"]}/>
  </div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
   <ChoiceSelect icon="▶" label="Platform" value={form.platform} onChange={v=>set("platform",v)} options={["TikTok / Instagram Reels","TikTok","Instagram Reels","YouTube Shorts","Facebook"]}/>
   <ChoiceSelect icon="✦" label="Style / tone" value={form.tone} onChange={v=>set("tone",v)} options={["Energetic","Premium","Professional","Friendly","Minimal","Luxury"]}/>
  </div>

  <section style={{...cardStyle,padding:14}}>
   <SectionLabel icon="◷">Duration <span style={{fontWeight:700,color:"#8197bc"}}>(up to 60 seconds)</span></SectionLabel>
   <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginBottom:16}}>{durationButtons.map(v=><button key={v} type="button" onClick={()=>set("duration",v)} style={{padding:"14px 4px",borderRadius:12,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.04)",color:C.text,fontWeight:850,fontSize:13,...(form.duration===v?activeGlow:{})}}>{v} sec</button>)}</div>
   <SectionLabel icon="⌗">Video ratio</SectionLabel>
   <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{ratios.map(r=><button key={r.v} type="button" onClick={()=>set("aspectRatio",r.v)} style={{padding:"12px 5px",borderRadius:13,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.035)",color:C.text,...(form.aspectRatio===r.v?activeGlow:{})}}><div style={{fontSize:26,lineHeight:1,marginBottom:6}}>{r.icon}</div><div style={{fontWeight:900,fontSize:13}}>{r.v}</div><div style={{fontSize:10,color:form.aspectRatio===r.v?"#eaf6ff":"#9cb0cf",marginTop:2}}>{r.name}</div></button>)}</div>
  </section>

  <section style={{...cardStyle,padding:14,display:"grid",gap:11}}>
   <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><div style={{display:"flex",alignItems:"center",gap:9}}><span style={{fontSize:25,color:C.purple,fontWeight:900}}>Tₜ</span><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>ON-SCREEN TEXT</div></div><button type="button" onClick={suggestWithAI} disabled={busyPlan} style={{padding:"8px 11px",borderRadius:11,border:"1px solid #8f4dff",background:"linear-gradient(135deg,rgba(129,48,255,.65),rgba(20,111,218,.65))",color:"#fff",fontSize:11,fontWeight:850,opacity:busyPlan?.6:1}}>{busyPlan?"Suggesting...":"Suggest with AI ✨"}</button></div>
   <label><div style={{fontSize:10,color:"#9fb1cf",fontWeight:900,marginBottom:6}}>HEADLINE</div><input value={form.headline} onChange={e=>set("headline",e.target.value)} style={inputStyle}/></label>
   <label><div style={{fontSize:10,color:"#9fb1cf",fontWeight:900,marginBottom:6}}>SHORT MESSAGE</div><input value={form.subtext} onChange={e=>set("subtext",e.target.value)} style={inputStyle}/></label>
   <label><div style={{fontSize:10,color:"#9fb1cf",fontWeight:900,marginBottom:6}}>CALL TO ACTION</div><input value={form.cta} onChange={e=>set("cta",e.target.value)} style={inputStyle}/></label>
  </section>

  <section style={{...cardStyle,padding:14}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10}}><div><div style={{fontSize:12,color:C.cyan,fontWeight:900,display:"flex",gap:8,alignItems:"center"}}>🖼 UPLOAD PHOTOS / SHORT CLIPS</div><div style={{fontSize:11,color:C.muted,lineHeight:1.45,marginTop:6}}>Add up to 8 photos or short videos. BizAI will turn them into scenes in the same order you select them.</div></div><div style={{fontSize:10,padding:"6px 9px",borderRadius:10,background:"rgba(255,255,255,.05)",border:`1px solid ${C.line}`,color:"#b9c7df",whiteSpace:"nowrap"}}>Max 8 files</div></div>
   <input ref={fileRef} type="file" accept="image/*,video/*" multiple onChange={chooseMedia} style={{display:"none"}}/>
   <button type="button" onClick={()=>fileRef.current?.click()} style={{width:"100%",marginTop:12,padding:"13px",borderRadius:14,border:"1px dashed #9462ff",background:"rgba(31,38,83,.45)",color:"#fff"}}><span style={{display:"inline-flex",alignItems:"center",gap:10,padding:"9px 18px",borderRadius:12,background:"linear-gradient(135deg,#923cff,#18bef0)",boxShadow:"0 0 18px rgba(100,65,255,.25)",fontWeight:900}}>☁︎ Choose Files</span><div style={{fontSize:10,color:"#a8b8d1",marginTop:8}}>JPG, PNG, MP4, MOV (max 100MB each)</div></button>
   {previewItems.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:7,marginTop:12}}>{previewItems.map((m,i)=><div key={m.url} style={{position:"relative",aspectRatio:"1 / 1",borderRadius:10,overflow:"hidden",border:`1px solid ${C.line}`,background:"#071329"}}>{m.isVideo?<video src={m.url} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={m.url} alt={m.file.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>}<button type="button" onClick={()=>removeMedia(i)} style={{position:"absolute",right:3,top:3,width:22,height:22,borderRadius:"50%",border:"1px solid rgba(255,255,255,.45)",background:"rgba(0,0,0,.72)",color:"#fff",fontSize:12,fontWeight:900}}>×</button><span style={{position:"absolute",left:4,bottom:3,fontSize:11,textShadow:"0 1px 4px #000"}}>{m.isVideo?"▶":"▧"}</span></div>)}</div>}
  </section>

  <button type="button" disabled={busyVideo} onClick={createFreeVideo} style={{width:"100%",padding:"16px",borderRadius:16,border:"1px solid rgba(89,224,255,.65)",background:"linear-gradient(135deg,#8c32ff,#487aff 50%,#13c9e7)",color:"#fff",fontWeight:950,fontSize:17,boxShadow:"0 0 22px rgba(84,73,255,.28)",opacity:busyVideo?.6:1}}>{busyVideo?"Creating video...":"✨ Create free video  →"}</button>
  <div style={{textAlign:"center",fontSize:12,color:C.cyan,fontWeight:900}}>{status}</div>
  {error&&<div style={{padding:12,borderRadius:13,color:"#ffc3cc",background:"rgba(255,80,100,.09)",border:"1px solid rgba(255,100,120,.25)",fontSize:12,lineHeight:1.45}}>{error}</div>}
  <canvas ref={canvasRef} style={{display:"none"}}/>
  {video&&<section style={{...cardStyle,padding:14,display:"grid",gap:10}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>VIDEO PREVIEW · {video.format}</div><video src={video.url} controls playsInline preload="metadata" style={{width:"100%",borderRadius:16,background:"#000",border:`1px solid ${C.line}`}}/><a href={video.url} download={video.fileName} style={{display:"block",textDecoration:"none",textAlign:"center",padding:"13px",borderRadius:13,background:"linear-gradient(135deg,#8c32ff,#18c6ea)",color:"#fff",fontWeight:900}}>Download video</a><div style={{fontSize:11,color:C.muted,lineHeight:1.5}}>On iPhone, if the video opens instead of downloading, use Share → Save to Files or Save Video.</div></section>}
 </main>;
}
