import React,{useRef,useState}from"react";

const AI_API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
const C={text:"#f7f9ff",muted:"#91a5ca",blue:"#4d86ff",cyan:"#50d9ff",line:"rgba(255,255,255,.10)"};
const input={width:"100%",boxSizing:"border-box",padding:"14px",borderRadius:14,border:`1px solid ${C.line}`,background:"rgba(255,255,255,.055)",color:C.text,fontSize:15,outline:"none"};
const btn={width:"100%",padding:"14px 16px",borderRadius:15,border:0,background:"linear-gradient(135deg,#397cff,#6c5cff)",color:"white",fontWeight:850,fontSize:15};
const card={padding:16,borderRadius:18,border:`1px solid ${C.line}`,background:"linear-gradient(145deg,rgba(18,43,84,.96),rgba(8,24,52,.96))"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function Field({label,value,onChange,placeholder}){return <label style={{display:"block"}}><div style={{fontSize:11,color:C.muted,fontWeight:850,marginBottom:7}}>{label}</div><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={input}/></label>}
function TextArea({label,value,onChange,placeholder,rows=7}){return <label style={{display:"block"}}><div style={{fontSize:11,color:C.muted,fontWeight:850,marginBottom:7}}>{label}</div><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={rows} style={{...input,resize:"vertical",lineHeight:1.5}}/></label>}
async function jsonFetch(url,options){const r=await fetch(url,options);let d;try{d=await r.json()}catch{throw new Error("The server returned an invalid response.")}if(!r.ok)throw new Error(d?.error||"Request failed.");return d}

function pickRecorderMime(){const candidates=["video/mp4;codecs=h264","video/mp4","video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"];return candidates.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||""}
function dimensions(ratio){if(ratio==="16:9")return[960,540];if(ratio==="1:1")return[720,720];return[540,960]}
function drawCover(ctx,source,w,h){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)return;const scale=Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(source,(w-dw)/2,(h-dh)/2,dw,dh)}
function roundedRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=3){const words=String(text||"").split(/\s+/).filter(Boolean);let line="",lines=[];for(const word of words){const t=line?`${line} ${word}`:word;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=t}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight))}
function drawFrame(ctx,source,w,h,form,index,total){ctx.fillStyle="#071329";ctx.fillRect(0,0,w,h);drawCover(ctx,source,w,h);const g=ctx.createLinearGradient(0,h*.45,0,h);g.addColorStop(0,"rgba(3,8,20,0)");g.addColorStop(1,"rgba(3,8,20,.88)");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const pad=Math.round(w*.065);ctx.fillStyle="#fff";ctx.font=`900 ${Math.round(w*.075)}px system-ui,sans-serif`;wrapText(ctx,form.headline||form.title||"Your Ad",pad,h*.72,w-pad*2,Math.round(w*.085),2);ctx.font=`600 ${Math.round(w*.036)}px system-ui,sans-serif`;ctx.fillStyle="rgba(255,255,255,.88)";wrapText(ctx,form.subtext||form.goal||"",pad,h*.84,w-pad*2,Math.round(w*.05),2);const cta=form.cta||"Message us today";ctx.font=`800 ${Math.round(w*.035)}px system-ui,sans-serif`;const tw=ctx.measureText(cta).width,ph=Math.round(w*.045),pv=Math.round(w*.026),boxH=pv*2+Math.round(w*.05),boxY=h-pad-boxH;ctx.fillStyle="#4d86ff";roundedRect(ctx,pad,boxY,Math.min(w-pad*2,tw+ph*2),boxH,Math.round(w*.03));ctx.fill();ctx.fillStyle="#fff";ctx.fillText(cta,pad+ph,h-pad-pv);ctx.fillStyle="rgba(255,255,255,.75)";ctx.font=`700 ${Math.round(w*.024)}px system-ui,sans-serif`;ctx.fillText(`${index+1}/${total}`,w-pad-Math.round(w*.07),pad+Math.round(w*.03))}
async function imageFromFile(file){const url=URL.createObjectURL(file);const img=new Image();img.decoding="async";img.src=url;await img.decode();return{type:"image",source:img,url}}
async function videoFromFile(file){const url=URL.createObjectURL(file);const v=document.createElement("video");v.src=url;v.muted=true;v.playsInline=true;v.preload="auto";await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=()=>reject(new Error(`Could not read ${file.name}`))});return{type:"video",source:v,url}}

export default function VideoAdStudioV2({profile={}}){
 const canvasRef=useRef(null);
 const[form,setForm]=useState({title:profile.business?`${profile.business} Video Ad`:"",instructions:"",audience:"",goal:"",platform:"TikTok / Instagram Reels",duration:"10",tone:"Energetic",aspectRatio:"9:16",headline:profile.business||"",subtext:profile.product||"",cta:"Message us today"});
 const[files,setFiles]=useState([]),[plan,setPlan]=useState(""),[video,setVideo]=useState(null),[busyPlan,setBusyPlan]=useState(false),[busyVideo,setBusyVideo]=useState(false),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 function chooseMedia(e){const picked=Array.from(e.target.files||[]).slice(0,8);setFiles(picked);setVideo(null);setError("");setStatus(picked.length?`${picked.length} media item${picked.length===1?"":"s"} ready`:"Ready")}
 async function buildPlan(){if(!form.instructions.trim()){setError("Describe the video ad you want first.");return}setBusyPlan(true);setError("");setPlan("");setStatus("Building your ad plan...");try{const d=await jsonFetch(`${AI_API}/api/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"video-ad",businessName:profile.business,product:profile.product,price:profile.price,location:profile.location,title:form.title,instructions:form.instructions,audience:form.audience,goal:form.goal,platform:form.platform,duration:`${form.duration} seconds`,tone:form.tone})});setPlan(d.text||"");setStatus(d.mode==="lite"?"Ad plan ready · Lite mode":"Ad plan ready")}catch(e){setError(e.message);setStatus("Plan stopped")}finally{setBusyPlan(false)}}
 async function createFreeVideo(){if(!files.length){setError("Upload at least one photo or short video first.");return}if(!window.MediaRecorder){setError("This browser cannot export video yet. Try Chrome, Safari, or another modern browser.");return}setBusyVideo(true);setError("");if(video?.url)URL.revokeObjectURL(video.url);setVideo(null);setStatus("Preparing your free video...");const loaded=[];try{for(const file of files)loaded.push(file.type.startsWith("video/")?await videoFromFile(file):await imageFromFile(file));const[w,h]=dimensions(form.aspectRatio),canvas=canvasRef.current,ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const stream=canvas.captureStream(30),mime=pickRecorderMime(),chunks=[];const recorder=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:4_000_000}:{videoBitsPerSecond:4_000_000});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const stopped=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||new Error("Video export failed."))});recorder.start(250);const totalMs=Math.max(3000,Number(form.duration||10)*1000),slotMs=Math.max(900,totalMs/loaded.length);for(let i=0;i<loaded.length;i++){const item=loaded[i],endAt=performance.now()+slotMs;if(item.type==="video"){item.source.currentTime=0;try{await item.source.play()}catch{};while(performance.now()<endAt){drawFrame(ctx,item.source,w,h,form,i,loaded.length);await sleep(33)}item.source.pause()}else{while(performance.now()<endAt){drawFrame(ctx,item.source,w,h,form,i,loaded.length);await sleep(33)}}setStatus(`Rendering scene ${i+1} of ${loaded.length}...`)}recorder.stop();await stopped;const outMime=recorder.mimeType||mime||"video/webm",blob=new Blob(chunks,{type:outMime}),url=URL.createObjectURL(blob),ext=outMime.includes("mp4")?"mp4":"webm";setVideo({url,fileName:`bizai-${(form.title||"video-ad").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"video-ad"}.${ext}`,format:ext.toUpperCase(),size:blob.size});setStatus(`${ext.toUpperCase()} video ready · no paid AI used`)}catch(e){setError(e.message||"Could not create the video.");setStatus("Video creation stopped")}finally{loaded.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch{}});setBusyVideo(false)}}
 return <main style={{padding:"20px 18px 45px",display:"flex",flexDirection:"column",gap:14,color:C.text}}>
  <div><div style={{display:"inline-block",padding:"5px 9px",borderRadius:999,background:"rgba(81,215,255,.12)",border:"1px solid rgba(81,215,255,.3)",color:C.cyan,fontSize:11,fontWeight:850}}>FREE VIDEO MAKER</div><h1 style={{fontSize:26,margin:"10px 0 5px"}}>Video Ad Studio</h1><p style={{fontSize:13,color:C.muted,lineHeight:1.55,margin:0}}>Create a real downloadable ad from your own photos and short clips. This mode does not use fal or paid AI video credits.</p></div>
  <Field label="AD / CAMPAIGN NAME" value={form.title} onChange={v=>set("title",v)} placeholder="e.g. ASD Cuts Transformation Ad"/>
  <TextArea label="DESCRIBE THE VIDEO AD YOU WANT" value={form.instructions} onChange={v=>set("instructions",v)} placeholder="Example: Start with a before-and-after haircut transformation, show clean fades and beard shaping, then end with a WhatsApp booking CTA."/>
  <Field label="TARGET AUDIENCE" value={form.audience} onChange={v=>set("audience",v)} placeholder="e.g. Men aged 18–35 in Kaduna"/>
  <Field label="GOAL" value={form.goal} onChange={v=>set("goal",v)} placeholder="e.g. Get WhatsApp bookings"/>
  <Field label="PLATFORM" value={form.platform} onChange={v=>set("platform",v)} placeholder="TikTok / Instagram Reels"/>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label><div style={{fontSize:11,color:C.muted,fontWeight:850,marginBottom:7}}>VIDEO LENGTH</div><select value={form.duration} onChange={e=>set("duration",e.target.value)} style={input}><option value="5">5 seconds</option><option value="10">10 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option></select></label><label><div style={{fontSize:11,color:C.muted,fontWeight:850,marginBottom:7}}>VIDEO RATIO</div><select value={form.aspectRatio} onChange={e=>set("aspectRatio",e.target.value)} style={input}><option value="9:16">9:16 Vertical</option><option value="16:9">16:9 Landscape</option><option value="1:1">1:1 Square</option></select></label></div>
  <Field label="STYLE / TONE" value={form.tone} onChange={v=>set("tone",v)} placeholder="Energetic, premium, cinematic..."/>
  <div style={{...card,display:"flex",flexDirection:"column",gap:11}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>ON-SCREEN TEXT</div><Field label="HEADLINE" value={form.headline} onChange={v=>set("headline",v)} placeholder="e.g. ASD CUTS"/><Field label="SHORT MESSAGE" value={form.subtext} onChange={v=>set("subtext",v)} placeholder="e.g. Sharp cuts. Clean style."/><Field label="CALL TO ACTION" value={form.cta} onChange={v=>set("cta",v)} placeholder="e.g. Book now on WhatsApp"/></div>
  <label style={{...card,display:"block"}}><div style={{fontSize:12,color:C.cyan,fontWeight:900,marginBottom:7}}>UPLOAD PHOTOS / SHORT CLIPS</div><div style={{fontSize:11,color:C.muted,lineHeight:1.5,marginBottom:10}}>Add up to 8 photos or short videos. BizAI will turn them into scenes in the same order you select them.</div><input type="file" accept="image/*,video/*" multiple onChange={chooseMedia} style={{color:C.muted,maxWidth:"100%"}}/>{files.length>0&&<div style={{fontSize:11,color:"#b8c8e8",marginTop:9}}>{files.map(f=>f.name).join(" · ")}</div>}</label>
  <button type="button" disabled={busyPlan||busyVideo} onClick={buildPlan} style={{...btn,opacity:(busyPlan||busyVideo)?0.55:1}}>{busyPlan?"Building ad plan...":"1. Build video ad plan"}</button>
  <button type="button" disabled={busyVideo||busyPlan} onClick={createFreeVideo} style={{...btn,background:"linear-gradient(135deg,#715cff,#22c7e8)",opacity:(busyVideo||busyPlan)?0.55:1}}>{busyVideo?"Creating video...":"2. Create free video"}</button>
  <div style={{textAlign:"center",fontSize:12,color:C.cyan,fontWeight:800}}>{status}</div>
  <div style={{fontSize:11,color:C.muted,lineHeight:1.55,padding:"10px 12px",borderRadius:12,background:"rgba(80,217,255,.06)",border:"1px solid rgba(80,217,255,.12)"}}>Free mode uses your own media and renders on your device, so there is no fal charge. Paid AI-generated footage can return later as a credit-based Premium option.</div>
  {error&&<div style={{padding:13,borderRadius:14,color:"#ffc1c7",background:"rgba(255,80,100,.1)",border:"1px solid rgba(255,100,120,.25)",fontSize:13,lineHeight:1.45}}>{error}</div>}
  {plan&&<section><div style={{fontSize:12,color:C.cyan,fontWeight:900,marginBottom:8}}>VIDEO AD PLAN</div><div style={{...card,whiteSpace:"pre-wrap",fontSize:14,lineHeight:1.6}}>{plan}</div></section>}
  <canvas ref={canvasRef} style={{display:"none"}}/>
  {video&&<section style={{display:"flex",flexDirection:"column",gap:10}}><div style={{fontSize:12,color:C.cyan,fontWeight:900}}>VIDEO PREVIEW · {video.format}</div><video src={video.url} controls playsInline preload="metadata" style={{width:"100%",borderRadius:18,background:"#000",border:`1px solid ${C.line}`}}/><a href={video.url} download={video.fileName} style={{...btn,textDecoration:"none",textAlign:"center",boxSizing:"border-box"}}>Download video</a><div style={{fontSize:11,color:C.muted,lineHeight:1.5}}>If your iPhone opens the video instead of downloading it, use Share → Save to Files or Save Video. Safari usually exports MP4; some Android browsers may export WebM.</div></section>}
 </main>;
}