import React,{useState}from"react";
const API=(import.meta.env.VITE_API_URL||"").trim().replace(/\/$/,"");
const box={width:"100%",boxSizing:"border-box",padding:"14px",borderRadius:14,border:"1px solid rgba(255,255,255,.12)",background:"#0d1d3a",color:"white",fontSize:15};
export default function WebsiteAIv2({profile={}}){
 const[mode,setMode]=useState("bizai"),[form,setForm]=useState({description:"",businessName:profile.business||"",businessType:"",services:profile.product||"",location:profile.location||"",contact:"",requirements:""}),[refs,setRefs]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState("Ready"),[html,setHtml]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const choose=async e=>{const fs=[...(e.target.files||[])].slice(0,4);const imgs=await Promise.all(fs.map(file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(file)})));setRefs(imgs)};
 const selectMode=(next)=>{setMode(next);setError("");setStatus(next==="bizai"?"Mode: BizAI designs it":"Mode: I'll describe it")};
 const generate=async()=>{if(loading)return;if(!form.businessName.trim()&&!form.description.trim()){setError("Add a business name or describe the website first.");setStatus("Add your website details first");return}if(!API){setError("BizAI server connection is missing.");setStatus("Server connection missing");return}setLoading(true);setError("");setHtml("");setStatus("Connecting to BizAI...");try{const r=await fetch(`${API}/api/generate-website`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,designMode:mode,referenceImages:refs})});setStatus(`Server replied: ${r.status}`);const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error("Server returned an invalid response.")}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);if(!d.html)throw new Error("No website was returned.");setHtml(d.html);setStatus("Website ready")}catch(e){setError(e.message||"Generation failed");setStatus("Stopped")}finally{setLoading(false)}};
 const download=()=>{const u=URL.createObjectURL(new Blob([html],{type:"text/html"}));const a=document.createElement("a");a.href=u;a.download="bizai-website.html";a.click();URL.revokeObjectURL(u)};
 return <main style={{padding:"20px 18px 45px",color:"#f5f8ff"}}>
  <div style={{display:"inline-block",padding:"5px 9px",borderRadius:999,background:"rgba(81,215,255,.12)",border:"1px solid rgba(81,215,255,.3)",color:"#51d7ff",fontSize:11,fontWeight:800,marginBottom:10}}>V2 ACTIVE</div>
  <h1 style={{fontSize:25,margin:"0 0 6px"}}>Website AI <span style={{fontSize:11,color:"#51d7ff"}}>NEW</span></h1><p style={{color:"#91a4c7",fontSize:13,lineHeight:1.55,marginTop:0}}>Describe everything you want on your website. Choose whether BizAI designs it for you or follows your own design instructions.</p>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,margin:"18px 0 10px"}}><button type="button" onClick={()=>selectMode("bizai")} style={{...box,border:mode==="bizai"?"2px solid #4f8cff":box.border,textAlign:"left"}}>✨ <b>BizAI designs it</b><small style={{display:"block",color:"#91a4c7",marginTop:6}}>Let BizAI choose the look.</small></button><button type="button" onClick={()=>selectMode("custom")} style={{...box,border:mode==="custom"?"2px solid #4f8cff":box.border,textAlign:"left"}}>🎨 <b>I'll describe it</b><small style={{display:"block",color:"#91a4c7",marginTop:6}}>Give your exact design idea.</small></button></div>
  <div style={{fontSize:12,color:"#51d7ff",fontWeight:800,marginBottom:16}}>CURRENT MODE: {mode==="bizai"?"BizAI designs it":"I'll describe it"}</div>
  <label style={{fontSize:12,fontWeight:800,color:"#51d7ff"}}>DESCRIBE EVERYTHING YOU WANT</label><textarea value={form.description} onChange={e=>set("description",e.target.value)} rows="6" placeholder={mode==="bizai"?"Tell BizAI about the business, pages and features you need...":"Describe layout, colors, sections, buttons, style and everything you want..."} style={{...box,marginTop:7,resize:"vertical"}}/>
  <div style={{margin:"14px 0",padding:14,border:"1px dashed #4f8cff",borderRadius:15}}><b style={{fontSize:13}}>Add images or screenshots (optional)</b><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={choose} style={{display:"block",marginTop:10,color:"#91a4c7"}}/>{refs.length>0&&<div style={{fontSize:12,color:"#51d7ff",marginTop:8}}>{refs.length} image(s) ready</div>}</div>
  {[['businessName','BUSINESS NAME','e.g. King’s Cut'],['businessType','BUSINESS TYPE','e.g. Barber shop'],['services','SERVICES / PRODUCTS','What do you offer?'],['location','LOCATION','e.g. Kaduna'],['contact','CONTACT','WhatsApp, phone or email'],['requirements','OTHER REQUIREMENTS','Booking, gallery, FAQ...']].map(([k,l,p])=><label key={k} style={{display:"block",marginTop:12,fontSize:12,color:"#91a4c7",fontWeight:700}}>{l}<input value={form[k]} onChange={e=>set(k,e.target.value)} placeholder={p} style={{...box,marginTop:7}}/></label>)}
  <button type="button" onClick={generate} disabled={loading} style={{width:"100%",marginTop:18,padding:15,border:0,borderRadius:15,color:"white",fontWeight:850,fontSize:15,background:"linear-gradient(135deg,#3f7cff,#725cff)",opacity:loading?0.6:1}}>{loading?"Building website...":"Generate website"}</button><div style={{textAlign:"center",fontSize:12,color:"#51d7ff",marginTop:9}}>{status}</div>
  {error&&<div style={{marginTop:12,padding:13,borderRadius:13,background:"rgba(255,90,110,.12)",border:"1px solid rgba(255,90,110,.35)",color:"#ffb4bd",fontSize:13}}>{error}</div>}
  {html&&<section style={{marginTop:20}}><b>Live preview</b><iframe title="Generated website" srcDoc={html} sandbox="allow-scripts" style={{width:"100%",height:500,border:0,borderRadius:16,background:"white",marginTop:10}}/><div style={{display:"flex",gap:8,marginTop:10}}><button type="button" onClick={download} style={{...box,width:"auto"}}>Export HTML</button><button type="button" onClick={()=>navigator.clipboard?.writeText(html)} style={{...box,width:"auto"}}>Copy code</button></div></section>}
 </main>;
}
