import React, { useState } from "react";

const C={blue:"#4f8cff",cyan:"#51d7ff",text:"#f5f8ff",muted:"#91a4c7",line:"rgba(255,255,255,.09)"};
const input={width:"100%",boxSizing:"border-box",padding:"14px 15px",border:`1px solid ${C.line}`,borderRadius:15,background:"rgba(255,255,255,.055)",color:C.text,fontSize:15,outline:"none"};
const API_BASE=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");

function Field({label,value,onChange,placeholder}){return <label><div style={{fontSize:12,fontWeight:700,color:C.muted,marginBottom:7}}>{label}</div><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={input}/></label>}
function Btn({children,onClick,disabled,secondary=false}){return <button onClick={onClick} disabled={disabled} style={{border:secondary?`1px solid ${C.line}`:"none",borderRadius:14,padding:"12px 16px",background:secondary?"rgba(255,255,255,.055)":"linear-gradient(135deg,#3f7cff,#6a65ff)",color:C.text,fontWeight:750,fontSize:14,opacity:disabled?.5:1}}>{children}</button>}

export default function WebsiteAI({profile={}}){
 const[mode,setMode]=useState("bizai");
 const[form,setForm]=useState({description:"",businessName:profile.business||"",businessType:"",services:profile.product||"",location:profile.location||"",contact:"",style:"",colors:"",requirements:""});
 const[images,setImages]=useState([]),[html,setHtml]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const pick=async e=>{const files=[...(e.target.files||[])].slice(0,4);setError("");const ok=files.filter(f=>/image\/(png|jpeg|webp)/.test(f.type));if(ok.length!==files.length){setError("Use PNG, JPEG or WebP images only.");return}try{const data=await Promise.all(ok.map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:f.name,data:r.result});r.onerror=reject;r.readAsDataURL(f)})));setImages(data)}catch{setError("One of the images could not be loaded.")}};
 const run=async()=>{if(!form.businessName.trim()&&!form.description.trim()){setError("Add a business name or describe the website first.");return}setLoading(true);setError("");try{const r=await fetch(`${API_BASE}/api/generate-website`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,designMode:mode,referenceImages:images.map(x=>x.data)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Website generation failed.");setHtml(d.html||"")}catch(e){setError(e.message)}finally{setLoading(false)}};
 const download=()=>{const u=URL.createObjectURL(new Blob([html],{type:"text/html"}));const a=document.createElement("a");a.href=u;a.download=`${(form.businessName||"website").replace(/\s+/g,"_")}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 return <div style={{padding:"20px 18px 40px",display:"flex",flexDirection:"column",gap:15}}>
  <div><div style={{fontSize:24,fontWeight:850}}>Build your website</div><div style={{fontSize:13,color:C.muted,lineHeight:1.55,marginTop:6}}>Tell BizAI everything you want: your business, pages, products, services, contact details, features and design ideas. You can change the website after it is generated.</div></div>
  <div style={{fontSize:13,fontWeight:800}}>How do you want to design it?</div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{[["bizai","✨","Let BizAI design it","Give BizAI the details and let it choose the visual direction."],["custom","🎨","I'll describe my design","Tell BizAI exactly how you want the website to look."]].map(([id,icon,title,desc])=><button key={id} onClick={()=>setMode(id)} style={{textAlign:"left",padding:14,borderRadius:18,border:`1px solid ${mode===id?C.blue:C.line}`,background:mode===id?"rgba(79,140,255,.16)":"rgba(255,255,255,.04)",color:C.text}}><div style={{fontSize:22}}>{icon}</div><div style={{fontWeight:800,fontSize:13,marginTop:8}}>{title}</div><div style={{fontSize:11,color:C.muted,lineHeight:1.4,marginTop:5}}>{desc}</div></button>)}</div>
  <label><div style={{fontSize:12,fontWeight:800,color:C.cyan,marginBottom:7}}>DESCRIBE EVERYTHING YOU WANT</div><textarea value={form.description} onChange={e=>set("description",e.target.value)} rows={6} placeholder={mode==="bizai"?"Tell us about the business and what the website needs. BizAI can choose the design for you...":"Describe the pages, layout, colors, style, buttons, images, animations and anything else you want..."} style={{...input,resize:"vertical"}}/></label>
  <div style={{padding:14,border:`1px dashed ${C.blue}`,borderRadius:17,background:"rgba(79,140,255,.07)"}}><div style={{fontWeight:800,fontSize:13}}>Add visual references <span style={{color:C.muted,fontWeight:500}}>(optional)</span></div><div style={{fontSize:11,color:C.muted,lineHeight:1.45,margin:"5px 0 10px"}}>Upload up to 4 screenshots, logos, product photos or design references. BizAI will use them as inspiration.</div><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={pick} style={{color:C.muted,fontSize:12}}/>{images.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginTop:11}}>{images.map((x,i)=><div key={i} style={{position:"relative"}}><img src={x.data} alt="Reference" style={{width:"100%",height:64,objectFit:"cover",borderRadius:10,border:`1px solid ${C.line}`}}/><button onClick={()=>setImages(v=>v.filter((_,n)=>n!==i))} style={{position:"absolute",right:3,top:3,border:0,borderRadius:20,background:"rgba(0,0,0,.72)",color:"white",width:20,height:20}}>×</button></div>)}</div>}</div>
  <Field label="BUSINESS NAME" value={form.businessName} onChange={v=>set("businessName",v)} placeholder="e.g. King's Cut"/><Field label="BUSINESS TYPE" value={form.businessType} onChange={v=>set("businessType",v)} placeholder="e.g. Barber shop"/><Field label="SERVICES / PRODUCTS" value={form.services} onChange={v=>set("services",v)} placeholder="What do you offer?"/><Field label="LOCATION" value={form.location} onChange={v=>set("location",v)} placeholder="e.g. Kaduna"/><Field label="CONTACT" value={form.contact} onChange={v=>set("contact",v)} placeholder="WhatsApp, phone or email"/>
  {mode==="custom"&&<><Field label="STYLE" value={form.style} onChange={v=>set("style",v)} placeholder="Modern, luxury, playful, minimal..."/><Field label="COLORS" value={form.colors} onChange={v=>set("colors",v)} placeholder="Black and gold, blue and white..."/></>}
  <Field label="OTHER REQUIREMENTS" value={form.requirements} onChange={v=>set("requirements",v)} placeholder="Booking button, gallery, menu, FAQ..."/>
  <Btn onClick={run} disabled={loading}>{loading?"BizAI is building your website...":"Generate website"}</Btn>
  {error&&<div style={{padding:13,borderRadius:14,background:"rgba(255,111,125,.1)",border:"1px solid rgba(255,111,125,.3)",color:"#ffb2ba",fontSize:13}}>{error}</div>}
  {html&&<><div style={{fontWeight:800}}>Live preview</div><iframe title="Website preview" srcDoc={html} sandbox="allow-scripts" style={{width:"100%",height:460,border:0,borderRadius:20,background:"white"}}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Btn onClick={download}>Export website</Btn><Btn secondary onClick={()=>navigator.clipboard?.writeText(html)}>Copy code</Btn><Btn secondary onClick={run}>Regenerate</Btn></div><div style={{fontSize:11,color:C.muted,lineHeight:1.45}}>AI editing, version history and one-click publishing are the next Website AI stage.</div></>}
 </div>
}
